#ifndef SOURCE_BRANCH_LIST_H_
#define SOURCE_BRANCH_LIST_H_

/* DO NOT EDIT THIS FILE */

const callsite_t branchList[] = {
	[0] = {
		.address.value = 0,
		.callee = NULL
	}
};

#endif /* SOURCE_BRANCH_LIST_H_ */
