#ifndef SOURCE_OBJECT_LIST_H_
#define SOURCE_OBJECT_LIST_H_

/* DO NOT EDIT THIS FILE */

__attribute__((section(".data.$GLOBAL_REGION")))
instance_t instanceList[754];

const object_t objectList[] = {
    /* 0 - Vector Table */
    { &instanceList[0], NULL, 0x20000, 0x1, 304 },
    /* 1 - ResetISR */
    { &instanceList[1], &reviseItems[0], 0x20144, 0x1006, 92 },
    /* 2 - NMI_Handler */
    { &instanceList[2], NULL, 0x201a0, 0xa, 2 },
    /* 3 - MemManage_Handler */
    { &instanceList[3], NULL, 0x201a4, 0x12, 2 },
    /* 4 - BusFault_Handler */
    { &instanceList[4], NULL, 0x201a6, 0x16, 2 },
    /* 5 - UsageFault_Handler */
    { &instanceList[5], NULL, 0x201a8, 0x1a, 2 },
    /* 6 - SecureFault_Handler */
    { &instanceList[6], NULL, 0x201aa, 0x1e, 2 },
    /* 7 - DebugMon_Handler */
    { &instanceList[7], NULL, 0x201ae, 0x32, 2 },
    /* 8 - Reserved39_DriverIRQHandler */
    { &instanceList[8], NULL, 0x201b4, 0x0, 2 },
    /* 9 - data_init */
    { &instanceList[9], &reviseItems[4], 0x201b6, 0x800, 34 },
    /* 10 - bss_init */
    { &instanceList[10], &reviseItems[6], 0x201d8, 0x400, 20 },
    /* 11 - vRestoreContextOfFirstTask */
    { &instanceList[11], &reviseItems[7], 0x201f6, 0x400, 46 },
    /* 12 - vStartFirstTask */
    { &instanceList[12], NULL, 0x2022c, 0x0, 36 },
    /* 13 - PendSV_Handler */
    { &instanceList[13], &reviseItems[8], 0x2025c, 0x103a, 176 },
    /* 14 - SVC_Handler */
    { &instanceList[14], &reviseItems[12], 0x20314, 0x42e, 40 },
    /* 15 - StrFormatPrintf */
    { &instanceList[15], &reviseItems[13], 0x20340, 0x6c00, 1076 },
    /* 16 - pow */
    { &instanceList[16], &reviseItems[40], 0x20774, 0x16000, 1824 },
    /* 17 - vfscanf */
    { &instanceList[17], &reviseItems[128], 0x20e98, 0xe000, 2562 },
    /* 18 - _frexpl */
    { &instanceList[18], &reviseItems[184], 0x2189e, 0x800, 114 },
    /* 19 - _ldexpl */
    { &instanceList[19], &reviseItems[186], 0x21910, 0x800, 100 },
    /* 20 - frexp */
    { &instanceList[20], &reviseItems[188], 0x21978, 0x800, 112 },
    /* 21 - ldexp */
    { &instanceList[21], &reviseItems[190], 0x219e8, 0x800, 100 },
    /* 22 - a_malloc */
    { &instanceList[22], &reviseItems[192], 0x21a4c, 0xc00, 48 },
    /* 23 - a_mutex_init */
    { &instanceList[23], &reviseItems[195], 0x21a7c, 0xc00, 48 },
    /* 24 - a_mutex_acquire */
    { &instanceList[24], &reviseItems[198], 0x21aac, 0x1400, 80 },
    /* 25 - a_mutex_release */
    { &instanceList[25], &reviseItems[203], 0x21afc, 0x1400, 88 },
    /* 26 - a_mutex_delete */
    { &instanceList[26], &reviseItems[208], 0x21b54, 0xc00, 48 },
    /* 27 - a_event_delete */
    { &instanceList[27], &reviseItems[211], 0x21b84, 0xc00, 36 },
    /* 28 - a_event_init */
    { &instanceList[28], &reviseItems[214], 0x21ba8, 0xc00, 52 },
    /* 29 - a_event_clear */
    { &instanceList[29], &reviseItems[217], 0x21bdc, 0x1000, 52 },
    /* 30 - a_event_set */
    { &instanceList[30], &reviseItems[221], 0x21c10, 0x1000, 76 },
    /* 31 - a_event_wait */
    { &instanceList[31], &reviseItems[225], 0x21c5c, 0xc00, 76 },
    /* 32 - a_enter_critical */
    { &instanceList[32], &reviseItems[228], 0x21ca8, 0x1400, 84 },
    /* 33 - a_exit_critical */
    { &instanceList[33], &reviseItems[233], 0x21cfc, 0x1000, 76 },
    /* 34 - SPI_DMA_MasterUserCallback */
    { &instanceList[34], &reviseItems[237], 0x21d48, 0x800, 48 },
    /* 35 - WIFIDRVS_SPI_Transfer */
    { &instanceList[35], &reviseItems[239], 0x21d78, 0x2000, 256 },
    /* 36 - WIFIDRVS_SPI_Init */
    { &instanceList[36], &reviseItems[247], 0x21e78, 0x2c00, 544 },
    /* 37 - WIFIDRVS_SPI_GetDefaultConfig */
    { &instanceList[37], &reviseItems[258], 0x22098, 0xc00, 48 },
    /* 38 - WIFIDRVS_SPI_GetSPIConfig */
    { &instanceList[38], &reviseItems[261], 0x220c8, 0x1000, 72 },
    /* 39 - WIFIDRVS_SPI_InOutToken */
    { &instanceList[39], &reviseItems[265], 0x22110, 0x1000, 92 },
    /* 40 - WIFIDRVS_SPI_InOutBuffer */
    { &instanceList[40], &reviseItems[269], 0x2216c, 0x1400, 116 },
    /* 41 - WIFISHIELD_Init */
    { &instanceList[41], &reviseItems[274], 0x221e0, 0x2c00, 176 },
    /* 42 - WIFISHIELD_InitDrivers */
    { &instanceList[42], &reviseItems[285], 0x22290, 0x2c00, 228 },
    /* 43 - WIFISHIELD_PowerUp */
    { &instanceList[43], &reviseItems[296], 0x22374, 0x400, 28 },
    /* 44 - t_ipconfig_dhcpc_cb_enable */
    { &instanceList[44], &reviseItems[297], 0x22390, 0x800, 28 },
    /* 45 - Custom_Api_Dhcps_Success_Callback_Event */
    { &instanceList[45], &reviseItems[299], 0x223ac, 0x800, 56 },
    /* 46 - Custom_Api_Dhcpc_Success_Callback_Event */
    { &instanceList[46], &reviseItems[301], 0x223e4, 0x800, 92 },
    /* 47 - t_sendto */
    { &instanceList[47], &reviseItems[303], 0x22440, 0x3400, 564 },
    /* 48 - t_send */
    { &instanceList[48], &reviseItems[316], 0x22674, 0x1000, 132 },
    /* 49 - zero_copy_free */
    { &instanceList[49], &reviseItems[320], 0x226f8, 0xc00, 36 },
    /* 50 - Api_recvfrom */
    { &instanceList[50], &reviseItems[323], 0x2271c, 0x3c00, 468 },
    /* 51 - get_total_pkts_buffered */
    { &instanceList[51], &reviseItems[338], 0x228f0, 0x400, 32 },
    /* 52 - custom_receive_tcpip */
    { &instanceList[52], &reviseItems[339], 0x22910, 0x2800, 172 },
    /* 53 - custom_qapi */
    { &instanceList[53], &reviseItems[349], 0x229bc, 0x4800, 422 },
    /* 54 - Custom_GetRxRequest */
    { &instanceList[54], &reviseItems[367], 0x22b64, 0x2000, 128 },
    /* 55 - Custom_Driver_ContextInit */
    { &instanceList[55], &reviseItems[375], 0x22be4, 0x1c00, 156 },
    /* 56 - a_netbuf_append_fragment */
    { &instanceList[56], &reviseItems[382], 0x22c80, 0x800, 36 },
    /* 57 - a_netbuf_push */
    { &instanceList[57], &reviseItems[384], 0x22ca4, 0x800, 40 },
    /* 58 - a_netbuf_put */
    { &instanceList[58], &reviseItems[386], 0x22ccc, 0x800, 40 },
    /* 59 - a_netbuf_pull */
    { &instanceList[59], &reviseItems[388], 0x22cf4, 0x800, 40 },
    /* 60 - a_netbuf_trim */
    { &instanceList[60], &reviseItems[390], 0x22d1c, 0x800, 40 },
    /* 61 - Custom_Api_Rejoin */
    { &instanceList[61], &reviseItems[392], 0x22d44, 0x400, 16 },
    /* 62 - Custom_Api_Join */
    { &instanceList[62], &reviseItems[393], 0x22d54, 0x400, 16 },
    /* 63 - Custom_Api_Writemii */
    { &instanceList[63], &reviseItems[394], 0x22d64, 0x400, 16 },
    /* 64 - Custom_Api_Readmii */
    { &instanceList[64], &reviseItems[395], 0x22d74, 0x400, 16 },
    /* 65 - Custom_Api_Initialize */
    { &instanceList[65], &reviseItems[396], 0x22d84, 0x2c00, 240 },
    /* 66 - Custom_Api_GetDriverCxt */
    { &instanceList[66], &reviseItems[407], 0x22e74, 0x400, 16 },
    /* 67 - ath_ioctl_handler */
    { &instanceList[67], &reviseItems[408], 0x22e84, 0x1d400, 4804 },
    /* 68 - Custom_Api_Mediactl */
    { &instanceList[68], &reviseItems[525], 0x24148, 0x3c00, 792 },
    /* 69 - Custom_Api_DisconnectEvent */
    { &instanceList[69], &reviseItems[540], 0x24460, 0x1c00, 140 },
    /* 70 - Custom_Api_GpioDataEvent */
    { &instanceList[70], &reviseItems[547], 0x244ec, 0x800, 24 },
    /* 71 - Custom_Api_PfmDataEvent */
    { &instanceList[71], &reviseItems[549], 0x24504, 0x800, 24 },
    /* 72 - Custom_Api_PfmDataDoneEvent */
    { &instanceList[72], &reviseItems[551], 0x2451c, 0x800, 24 },
    /* 73 - Custom_Api_BitRateEvent_tx */
    { &instanceList[73], &reviseItems[553], 0x24534, 0x1000, 72 },
    /* 74 - wmi_set_control_ep */
    { &instanceList[74], &reviseItems[557], 0x2457c, 0x800, 32 },
    /* 75 - wmi_meta_add */
    { &instanceList[75], &reviseItems[559], 0x2459c, 0x2400, 164 },
    /* 76 - wmi_data_hdr_add */
    { &instanceList[76], &reviseItems[568], 0x24640, 0x1800, 160 },
    /* 77 - wmi_implicit_create_pstream */
    { &instanceList[77], &reviseItems[574], 0x246e0, 0xc00, 108 },
    /* 78 - wmi_data_hdr_remove */
    { &instanceList[78], &reviseItems[577], 0x2474c, 0x800, 32 },
    /* 79 - wmi_control_rx */
    { &instanceList[79], &reviseItems[579], 0x2476c, 0xe400, 1620 },
    /* 80 - wmi_cmd_send */
    { &instanceList[80], &reviseItems[636], 0x24dc0, 0x1c00, 148 },
    /* 81 - wmi_socket_cmd */
    { &instanceList[81], &reviseItems[643], 0x24e54, 0x800, 80 },
    /* 82 - dset_find */
    { &instanceList[82], &reviseItems[645], 0x24ea4, 0x400, 32 },
    /* 83 - dset_insert */
    { &instanceList[83], &reviseItems[646], 0x24ec4, 0x800, 56 },
    /* 84 - dset_fill */
    { &instanceList[84], &reviseItems[648], 0x24efc, 0x400, 52 },
    /* 85 - dset_get_first */
    { &instanceList[85], &reviseItems[649], 0x24f30, 0x800, 44 },
    /* 86 - dset_get_next */
    { &instanceList[86], &reviseItems[651], 0x24f5c, 0x800, 48 },
    /* 87 - dset_find_handle */
    { &instanceList[87], &reviseItems[653], 0x24f8c, 0x800, 36 },
    /* 88 - Strrcl_ChipUpFinish */
    { &instanceList[88], &reviseItems[655], 0x24fb0, 0x1c00, 172 },
    /* 89 - Strrcl_Recall */
    { &instanceList[89], &reviseItems[662], 0x2505c, 0x2c00, 184 },
    /* 90 - queue_empty */
    { &instanceList[90], &reviseItems[673], 0x25114, 0x400, 24 },
    /* 91 - find_socket_context_from_ssl */
    { &instanceList[91], &reviseItems[674], 0x2512c, 0x400, 36 },
    /* 92 - find_socket_context */
    { &instanceList[92], &reviseItems[675], 0x25150, 0x400, 40 },
    /* 93 - socket_context_init */
    { &instanceList[93], &reviseItems[676], 0x25178, 0x2400, 168 },
    /* 94 - clear_socket_context */
    { &instanceList[94], &reviseItems[685], 0x25220, 0x1000, 96 },
    /* 95 - send_stack_init */
    { &instanceList[95], &reviseItems[689], 0x25280, 0x800, 64 },
    /* 96 - move_power_state_to_maxperf */
    { &instanceList[96], &reviseItems[691], 0x252c0, 0x800, 64 },
    /* 97 - restore_power_state */
    { &instanceList[97], &reviseItems[693], 0x25300, 0x800, 76 },
    /* 98 - socket_set_driver_error */
    { &instanceList[98], &reviseItems[695], 0x2534c, 0x800, 40 },
    /* 99 - socket_get_driver_error */
    { &instanceList[99], &reviseItems[697], 0x25374, 0x800, 40 },
    /* 100 - blockForResponse */
    { &instanceList[100], &reviseItems[699], 0x2539c, 0x2000, 208 },
    /* 101 - Api_socket */
    { &instanceList[101], &reviseItems[707], 0x2546c, 0x2000, 244 },
    /* 102 - Api_connect */
    { &instanceList[102], &reviseItems[715], 0x25560, 0x1c00, 280 },
    /* 103 - Api_ipconfig */
    { &instanceList[103], &reviseItems[722], 0x25678, 0x1c00, 360 },
    /* 104 - Api_SockResponseEventRx */
    { &instanceList[104], &reviseItems[729], 0x257e0, 0x8c00, 1544 },
    /* 105 - aggr_init */
    { &instanceList[105], &reviseItems[764], 0x25de8, 0x400, 16 },
    /* 106 - aggr_recv_addba_req_evt */
    { &instanceList[106], &reviseItems[765], 0x25df8, 0x800, 60 },
    /* 107 - aggr_recv_delba_req_evt */
    { &instanceList[107], &reviseItems[767], 0x25e34, 0x800, 56 },
    /* 108 - aggr_reset_state */
    { &instanceList[108], &reviseItems[769], 0x25e6c, 0x800, 28 },
    /* 109 - HW_PowerUpDown */
    { &instanceList[109], &reviseItems[771], 0x25e88, 0x1800, 80 },
    /* 110 - HW_GetMboxAddress */
    { &instanceList[110], &reviseItems[777], 0x25ed8, 0x800, 36 },
    /* 111 - Htc_RxComplete */
    { &instanceList[111], &reviseItems[779], 0x25efc, 0xc00, 40 },
    /* 112 - Htc_ReadCreditCounter */
    { &instanceList[112], &reviseItems[782], 0x25f24, 0x1000, 92 },
    /* 113 - HTC_ProcessCpuInterrupt */
    { &instanceList[113], &reviseItems[786], 0x25f80, 0x1400, 120 },
    /* 114 - Htc_SendPacket */
    { &instanceList[114], &reviseItems[791], 0x25ff8, 0x1800, 148 },
    /* 115 - Htc_ProcessRecvHeader */
    { &instanceList[115], &reviseItems[797], 0x2608c, 0x2800, 436 },
    /* 116 - HTC_ConnectService */
    { &instanceList[116], &reviseItems[807], 0x26240, 0x1000, 184 },
    /* 117 - HTC_WaitTarget */
    { &instanceList[117], &reviseItems[811], 0x262f8, 0x1400, 104 },
    /* 118 - HTC_Start */
    { &instanceList[118], &reviseItems[816], 0x26360, 0x1000, 68 },
    /* 119 - ResetWriteBufferWaterMark.isra.0 */
    { &instanceList[119], &reviseItems[820], 0x263a4, 0xc00, 44 },
    /* 120 - Hcd_ProgramWriteBufferWaterMark */
    { &instanceList[120], &reviseItems[823], 0x263d0, 0x2400, 180 },
    /* 121 - Hcd_GetLookAhead */
    { &instanceList[121], &reviseItems[832], 0x26484, 0x1400, 128 },
    /* 122 - EnableDisableSPIIRQHwDetect */
    { &instanceList[122], &reviseItems[837], 0x26504, 0x1800, 108 },
    /* 123 - Hcd_BusInterrupt */
    { &instanceList[123], &reviseItems[843], 0x26570, 0x3c00, 412 },
    /* 124 - Hcd_Init */
    { &instanceList[124], &reviseItems[858], 0x2670c, 0x3400, 372 },
    /* 125 - Bus_InOutDescriptorSet */
    { &instanceList[125], &reviseItems[871], 0x26880, 0x1400, 136 },
    /* 126 - Hcd_DoPioExternalAccess */
    { &instanceList[126], &reviseItems[876], 0x26908, 0x3000, 264 },
    /* 127 - Hcd_ReadCPUInterrupt */
    { &instanceList[127], &reviseItems[888], 0x26a10, 0xc00, 80 },
    /* 128 - Hcd_ClearCPUInterrupt */
    { &instanceList[128], &reviseItems[891], 0x26a60, 0xc00, 68 },
    /* 129 - Hcd_Request */
    { &instanceList[129], &reviseItems[894], 0x26aa4, 0x1000, 148 },
    /* 130 - Driver_ReadRegDiag */
    { &instanceList[130], &reviseItems[898], 0x26b38, 0x1000, 80 },
    /* 131 - Driver_WriteRegDiag */
    { &instanceList[131], &reviseItems[902], 0x26b88, 0x1000, 80 },
    /* 132 - Driver_DumpAssertInfo */
    { &instanceList[132], &reviseItems[906], 0x26bd8, 0x1000, 124 },
    /* 133 - Driver_ContextInit */
    { &instanceList[133], &reviseItems[910], 0x26c54, 0x1800, 224 },
    /* 134 - Driver_DeInit */
    { &instanceList[134], &reviseItems[916], 0x26d34, 0x2800, 140 },
    /* 135 - Driver_GetTargetInfo */
    { &instanceList[135], &reviseItems[926], 0x26dc0, 0x800, 72 },
    /* 136 - Driver_BootComm */
    { &instanceList[136], &reviseItems[928], 0x26e08, 0x2800, 260 },
    /* 137 - Driver_Init */
    { &instanceList[137], &reviseItems[938], 0x26f0c, 0x6c00, 616 },
    /* 138 - Driver_CompleteRequest */
    { &instanceList[138], &reviseItems[965], 0x27174, 0x1000, 72 },
    /* 139 - Driver_RxReady */
    { &instanceList[139], &reviseItems[969], 0x271bc, 0x1c00, 260 },
    /* 140 - Driver_TxReady */
    { &instanceList[140], &reviseItems[976], 0x272c0, 0x2c00, 264 },
    /* 141 - Driver_Main */
    { &instanceList[141], &reviseItems[987], 0x273c8, 0x3400, 332 },
    /* 142 - Driver_CreateThread */
    { &instanceList[142], &reviseItems[1000], 0x27514, 0xc00, 72 },
    /* 143 - Driver_RxComplete */
    { &instanceList[143], &reviseItems[1003], 0x2755c, 0x1400, 76 },
    /* 144 - Driver_SubmitTxRequest */
    { &instanceList[144], &reviseItems[1008], 0x275a8, 0x1c00, 148 },
    /* 145 - bmiBufferSend */
    { &instanceList[145], &reviseItems[1015], 0x2763c, 0x1800, 200 },
    /* 146 - bmiBufferReceive */
    { &instanceList[146], &reviseItems[1021], 0x27704, 0x1400, 192 },
    /* 147 - BMIInit */
    { &instanceList[147], &reviseItems[1026], 0x277c4, 0x1000, 96 },
    /* 148 - BMIDone */
    { &instanceList[148], &reviseItems[1030], 0x27824, 0x1000, 104 },
    /* 149 - BMIGetTargetInfo */
    { &instanceList[149], &reviseItems[1034], 0x2788c, 0x1800, 144 },
    /* 150 - BMIWriteMemory */
    { &instanceList[150], &reviseItems[1040], 0x2791c, 0x1c00, 200 },
    /* 151 - BMIExecute */
    { &instanceList[151], &reviseItems[1047], 0x279e4, 0x2000, 172 },
    /* 152 - wmi_cmd_process */
    { &instanceList[152], &reviseItems[1055], 0x27a90, 0x1000, 88 },
    /* 153 - Api_BootProfile */
    { &instanceList[153], &reviseItems[1059], 0x27ae8, 0x800, 24 },
    /* 154 - Api_InitFinish */
    { &instanceList[154], &reviseItems[1061], 0x27b00, 0x800, 80 },
    /* 155 - Api_WMIInitFinish */
    { &instanceList[155], &reviseItems[1063], 0x27b50, 0x2000, 188 },
    /* 156 - Program_CountryCode */
    { &instanceList[156], &reviseItems[1071], 0x27c0c, 0x4400, 388 },
    /* 157 - program_mac_addr */
    { &instanceList[157], &reviseItems[1088], 0x27d90, 0x5800, 516 },
    /* 158 - security_ie_parse.constprop.0 */
    { &instanceList[158], &reviseItems[1110], 0x27f94, 0x400, 404 },
    /* 159 - Api_ParseInfoElem */
    { &instanceList[159], &reviseItems[1111], 0x28128, 0x1c00, 284 },
    /* 160 - Api_ProgramCountryCode */
    { &instanceList[160], &reviseItems[1118], 0x28244, 0x2000, 212 },
    /* 161 - Api_ProgramMacAddress */
    { &instanceList[161], &reviseItems[1126], 0x28318, 0x2000, 232 },
    /* 162 - Api_TxGetStatus */
    { &instanceList[162], &reviseItems[1134], 0x28400, 0xc00, 92 },
    /* 163 - Api_TxComplete */
    { &instanceList[163], &reviseItems[1137], 0x2845c, 0xc00, 60 },
    /* 164 - Api_RxComplete */
    { &instanceList[164], &reviseItems[1140], 0x28498, 0x2400, 256 },
    /* 165 - Api_HostDsetStoreEvent */
    { &instanceList[165], &reviseItems[1149], 0x28598, 0xc00, 96 },
    /* 166 - Api_HostDsetCreateEvent */
    { &instanceList[166], &reviseItems[1152], 0x285f8, 0x1800, 140 },
    /* 167 - Api_HostDsetWriteEvent */
    { &instanceList[167], &reviseItems[1158], 0x28684, 0x2000, 284 },
    /* 168 - Api_HostDsetReadbackEvent */
    { &instanceList[168], &reviseItems[1166], 0x287a0, 0x2800, 348 },
    /* 169 - Api_HostDsetSyncEvent */
    { &instanceList[169], &reviseItems[1176], 0x288fc, 0x1800, 132 },
    /* 170 - Api_HostDsetReadEvent */
    { &instanceList[170], &reviseItems[1182], 0x28980, 0x1800, 116 },
    /* 171 - Api_DsetOPEvent */
    { &instanceList[171], &reviseItems[1188], 0x289f4, 0x1400, 212 },
    /* 172 - Api_ReadyEvent */
    { &instanceList[172], &reviseItems[1193], 0x28ac8, 0xc00, 88 },
    /* 173 - DbgConsole_SendDataReliable */
    { &instanceList[173], &reviseItems[1196], 0x28b20, 0xc00, 80 },
    /* 174 - DbgConsole_Init */
    { &instanceList[174], &reviseItems[1199], 0x28b70, 0x1800, 160 },
    /* 175 - DbgConsole_Printf */
    { &instanceList[175], &reviseItems[1205], 0x28c10, 0x1000, 80 },
    /* 176 - aws_dhcpc_callback */
    { &instanceList[176], &reviseItems[1209], 0x28c60, 0x800, 64 },
    /* 177 - aws_connect_cb */
    { &instanceList[177], &reviseItems[1211], 0x28ca0, 0xc00, 124 },
    /* 178 - wlan_get_context */
    { &instanceList[178], &reviseItems[1214], 0x28d1c, 0x400, 12 },
    /* 179 - WIFI_On */
    { &instanceList[179], &reviseItems[1215], 0x28d28, 0x2c00, 212 },
    /* 180 - WIFI_ConnectAP */
    { &instanceList[180], &reviseItems[1226], 0x28dfc, 0x6400, 684 },
    /* 181 - WIFI_GetMode */
    { &instanceList[181], &reviseItems[1251], 0x290a8, 0x1000, 124 },
    /* 182 - WIFI_GetIP */
    { &instanceList[182], &reviseItems[1255], 0x29124, 0x800, 52 },
    /* 183 - WIFI_GetMAC */
    { &instanceList[183], &reviseItems[1257], 0x29158, 0x1400, 124 },
    /* 184 - publish_callback */
    { &instanceList[184], &reviseItems[1262], 0x291d4, 0x2c00, 168 },
    /* 185 - connect_to_server */
    { &instanceList[185], &reviseItems[1273], 0x2927c, 0x1400, 92 },
    /* 186 - task_client */
    { &instanceList[186], &reviseItems[1278], 0x292d8, 0x6000, 500 },
    /* 187 - WiFi_Initialize */
    { &instanceList[187], &reviseItems[1302], 0x294cc, 0x3800, 288 },
    /* 188 - task_main */
    { &instanceList[188], &reviseItems[1316], 0x295ec, 0x1400, 92 },
    /* 189 - main */
    { &instanceList[189], &reviseItems[1321], 0x29648, 0x1c00, 96 },
    /* 190 - mqtt_unpack_fixed_header */
    { &instanceList[190], &reviseItems[1328], 0x296a8, 0x400, 164 },
    /* 191 - mqtt_pack_fixed_header */
    { &instanceList[191], &reviseItems[1329], 0x2974c, 0x400, 152 },
    /* 192 - mqtt_unpack_connack_response */
    { &instanceList[192], &reviseItems[1330], 0x297e4, 0x1000, 60 },
    /* 193 - mqtt_init */
    { &instanceList[193], &reviseItems[1334], 0x29820, 0x1000, 140 },
    /* 194 - mqtt_mq_clean */
    { &instanceList[194], &reviseItems[1338], 0x298ac, 0xc00, 160 },
    /* 195 - __mqtt_ping */
    { &instanceList[195], &reviseItems[1341], 0x2994c, 0x1400, 96 },
    /* 196 - __mqtt_send */
    { &instanceList[196], &reviseItems[1346], 0x299ac, 0x3400, 492 },
    /* 197 - mqtt_pack_pubxxx_request */
    { &instanceList[197], &reviseItems[1359], 0x29b98, 0xc00, 100 },
    /* 198 - __mqtt_puback */
    { &instanceList[198], &reviseItems[1362], 0x29bfc, 0x1400, 108 },
    /* 199 - __mqtt_pubrec */
    { &instanceList[199], &reviseItems[1367], 0x29c68, 0x1400, 108 },
    /* 200 - __mqtt_pubrel */
    { &instanceList[200], &reviseItems[1372], 0x29cd4, 0x1400, 108 },
    /* 201 - __mqtt_pubcomp */
    { &instanceList[201], &reviseItems[1377], 0x29d40, 0x1400, 108 },
    /* 202 - mqtt_unpack_publish_response */
    { &instanceList[202], &reviseItems[1382], 0x29dac, 0xc00, 108 },
    /* 203 - mqtt_unpack_pubxxx_response */
    { &instanceList[203], &reviseItems[1385], 0x29e18, 0x800, 52 },
    /* 204 - mqtt_unpack_suback_response */
    { &instanceList[204], &reviseItems[1387], 0x29e4c, 0x800, 48 },
    /* 205 - mqtt_unpack_unsuback_response */
    { &instanceList[205], &reviseItems[1389], 0x29e7c, 0x800, 40 },
    /* 206 - mqtt_unpack_response */
    { &instanceList[206], &reviseItems[1391], 0x29ea4, 0x1c00, 136 },
    /* 207 - __mqtt_recv */
    { &instanceList[207], &reviseItems[1398], 0x29f2c, 0xa800, 980 },
    /* 208 - mqtt_sync */
    { &instanceList[208], &reviseItems[1440], 0x2a300, 0x2c00, 212 },
    /* 209 - mqtt_pack_connection_request */
    { &instanceList[209], &reviseItems[1451], 0x2a3d4, 0x3400, 424 },
    /* 210 - mqtt_connect */
    { &instanceList[210], &reviseItems[1464], 0x2a57c, 0x2000, 248 },
    /* 211 - mqtt_pack_publish_request */
    { &instanceList[211], &reviseItems[1472], 0x2a674, 0x1800, 192 },
    /* 212 - mqtt_publish */
    { &instanceList[212], &reviseItems[1478], 0x2a734, 0x2c00, 236 },
    /* 213 - mqtt_pack_subscribe_request */
    { &instanceList[213], &reviseItems[1489], 0x2a820, 0x1400, 224 },
    /* 214 - mqtt_subscribe */
    { &instanceList[214], &reviseItems[1494], 0x2a900, 0x2c00, 232 },
    /* 215 - mqtt_error_str */
    { &instanceList[215], &reviseItems[1505], 0x2a9e8, 0x400, 16 },
    /* 216 - mqtt_pal_sendall */
    { &instanceList[216], &reviseItems[1506], 0x2a9f8, 0x1000, 104 },
    /* 217 - mqtt_pal_recvall */
    { &instanceList[217], &reviseItems[1510], 0x2aa60, 0x1400, 120 },
    /* 218 - prvInsertBlockIntoFreeList */
    { &instanceList[218], &reviseItems[1515], 0x2aad8, 0x400, 76 },
    /* 219 - pvPortMalloc */
    { &instanceList[219], &reviseItems[1516], 0x2ab24, 0x1800, 292 },
    /* 220 - vPortFree */
    { &instanceList[220], &reviseItems[1522], 0x2ac48, 0x1800, 120 },
    /* 221 - prvTaskExitError */
    { &instanceList[221], &reviseItems[1528], 0x2acc0, 0xc00, 48 },
    /* 222 - vPortSetupTimerInterrupt */
    { &instanceList[222], &reviseItems[1531], 0x2acf0, 0x400, 52 },
    /* 223 - vPortYield */
    { &instanceList[223], &reviseItems[1532], 0x2ad24, 0x400, 24 },
    /* 224 - vPortEnterCritical */
    { &instanceList[224], &reviseItems[1533], 0x2ad3c, 0x800, 36 },
    /* 225 - vPortExitCritical */
    { &instanceList[225], &reviseItems[1535], 0x2ad60, 0xc00, 48 },
    /* 226 - SysTick_Handler */
    { &instanceList[226], &reviseItems[1538], 0x2ad90, 0xc3e, 44 },
    /* 227 - vPortSVCHandler_C */
    { &instanceList[227], &reviseItems[1541], 0x2adbc, 0x2000, 104 },
    /* 228 - pxPortInitialiseStack */
    { &instanceList[228], &reviseItems[1549], 0x2ae24, 0x400, 144 },
    /* 229 - xPortStartScheduler */
    { &instanceList[229], &reviseItems[1550], 0x2aeb4, 0x1400, 76 },
    /* 230 - xEventGroupClearBitsFromISR */
    { &instanceList[230], &reviseItems[1555], 0x2af00, 0x400, 16 },
    /* 231 - xEventGroupSetBitsFromISR */
    { &instanceList[231], &reviseItems[1556], 0x2af10, 0x400, 16 },
    /* 232 - vQueueAddToRegistry */
    { &instanceList[232], &reviseItems[1557], 0x2af20, 0x400, 40 },
    /* 233 - vQueueUnregisterQueue */
    { &instanceList[233], &reviseItems[1558], 0x2af48, 0x400, 44 },
    /* 234 - prvResetNextTaskUnblockTime */
    { &instanceList[234], &reviseItems[1559], 0x2af74, 0x400, 40 },
    /* 235 - prvAddCurrentTaskToDelayedList */
    { &instanceList[235], &reviseItems[1560], 0x2af9c, 0x1400, 128 },
    /* 236 - prvIdleTask */
    { &instanceList[236], &reviseItems[1565], 0x2b01c, 0x2000, 132 },
    /* 237 - xTaskCreate */
    { &instanceList[237], &reviseItems[1573], 0x2b0a0, 0x4800, 504 },
    /* 238 - vTaskStartScheduler */
    { &instanceList[238], &reviseItems[1591], 0x2b298, 0x1800, 128 },
    /* 239 - vTaskSuspendAll */
    { &instanceList[239], &reviseItems[1597], 0x2b318, 0x400, 16 },
    /* 240 - xTaskGetTickCount */
    { &instanceList[240], &reviseItems[1598], 0x2b328, 0x400, 12 },
    /* 241 - xTaskIncrementTick */
    { &instanceList[241], &reviseItems[1599], 0x2b334, 0x1800, 272 },
    /* 242 - xTaskResumeAll */
    { &instanceList[242], &reviseItems[1605], 0x2b444, 0x2800, 244 },
    /* 243 - vTaskDelay */
    { &instanceList[243], &reviseItems[1615], 0x2b538, 0x1800, 68 },
    /* 244 - vTaskSwitchContext */
    { &instanceList[244], &reviseItems[1621], 0x2b57c, 0x800, 116 },
    /* 245 - vTaskSuspend */
    { &instanceList[245], &reviseItems[1623], 0x2b5f0, 0x3000, 192 },
    /* 246 - vTaskPlaceOnEventList */
    { &instanceList[246], &reviseItems[1635], 0x2b6b0, 0xc00, 48 },
    /* 247 - vTaskPlaceOnUnorderedEventList */
    { &instanceList[247], &reviseItems[1638], 0x2b6e0, 0x1000, 76 },
    /* 248 - vTaskPlaceOnEventListRestricted */
    { &instanceList[248], &reviseItems[1642], 0x2b72c, 0xc00, 60 },
    /* 249 - xTaskRemoveFromEventList */
    { &instanceList[249], &reviseItems[1645], 0x2b768, 0x1400, 144 },
    /* 250 - vTaskRemoveFromUnorderedEventList */
    { &instanceList[250], &reviseItems[1650], 0x2b7f8, 0x1800, 140 },
    /* 251 - vTaskInternalSetTimeOutState */
    { &instanceList[251], &reviseItems[1656], 0x2b884, 0x400, 24 },
    /* 252 - xTaskCheckForTimeOut */
    { &instanceList[252], &reviseItems[1657], 0x2b89c, 0x1800, 120 },
    /* 253 - vTaskMissedYield */
    { &instanceList[253], &reviseItems[1663], 0x2b914, 0x400, 16 },
    /* 254 - xTaskGetCurrentTaskHandle */
    { &instanceList[254], &reviseItems[1664], 0x2b924, 0x400, 12 },
    /* 255 - xTaskGetSchedulerState */
    { &instanceList[255], &reviseItems[1665], 0x2b930, 0x800, 36 },
    /* 256 - xTaskPriorityInherit */
    { &instanceList[256], &reviseItems[1667], 0x2b954, 0xc00, 144 },
    /* 257 - xTaskPriorityDisinherit */
    { &instanceList[257], &reviseItems[1670], 0x2b9e4, 0x1400, 132 },
    /* 258 - vTaskPriorityDisinheritAfterTimeout */
    { &instanceList[258], &reviseItems[1675], 0x2ba68, 0x1400, 156 },
    /* 259 - uxTaskResetEventItemValue */
    { &instanceList[259], &reviseItems[1680], 0x2bb04, 0x400, 28 },
    /* 260 - pvTaskIncrementMutexHeldCount */
    { &instanceList[260], &reviseItems[1681], 0x2bb20, 0x400, 24 },
    /* 261 - prvCheckForValidListAndQueue */
    { &instanceList[261], &reviseItems[1682], 0x2bb38, 0x1800, 108 },
    /* 262 - prvInsertTimerInActiveList */
    { &instanceList[262], &reviseItems[1688], 0x2bba4, 0x800, 68 },
    /* 263 - xTimerCreateTimerTask */
    { &instanceList[263], &reviseItems[1690], 0x2bbe8, 0x1000, 76 },
    /* 264 - xTimerGenericCommand */
    { &instanceList[264], &reviseItems[1694], 0x2bc34, 0x1400, 96 },
    /* 265 - prvSwitchTimerLists */
    { &instanceList[265], &reviseItems[1699], 0x2bc94, 0x1800, 140 },
    /* 266 - prvTimerTask */
    { &instanceList[266], &reviseItems[1705], 0x2bd20, 0x6800, 572 },
    /* 267 - xTimerPendFunctionCallFromISR */
    { &instanceList[267], &reviseItems[1731], 0x2bf5c, 0x800, 48 },
    /* 268 - CLOCK_AttachClk */
    { &instanceList[268], &reviseItems[1733], 0x2bf8c, 0x400, 84 },
    /* 269 - CLOCK_SetupFROClocking */
    { &instanceList[269], &reviseItems[1734], 0x2bfe0, 0x800, 96 },
    /* 270 - CLOCK_SetFLASHAccessCyclesForFreq */
    { &instanceList[270], &reviseItems[1736], 0x2c040, 0x400, 232 },
    /* 271 - CLOCK_SetupExtClocking */
    { &instanceList[271], &reviseItems[1737], 0x2c128, 0x800, 68 },
    /* 272 - CLOCK_GetFro12MFreq */
    { &instanceList[272], &reviseItems[1739], 0x2c16c, 0x400, 28 },
    /* 273 - CLOCK_GetFro1MFreq */
    { &instanceList[273], &reviseItems[1740], 0x2c188, 0x400, 28 },
    /* 274 - CLOCK_GetExtClkFreq */
    { &instanceList[274], &reviseItems[1741], 0x2c1a4, 0x400, 28 },
    /* 275 - CLOCK_GetFroHfFreq */
    { &instanceList[275], &reviseItems[1742], 0x2c1c0, 0x400, 28 },
    /* 276 - CLOCK_GetOsc32KFreq */
    { &instanceList[276], &reviseItems[1743], 0x2c1dc, 0xc00, 68 },
    /* 277 - CLOCK_GetCoreSysClkFreq */
    { &instanceList[277], &reviseItems[1746], 0x2c220, 0x1c00, 88 },
    /* 278 - CLOCK_GetHsLspiClkFreq */
    { &instanceList[278], &reviseItems[1753], 0x2c278, 0x1c00, 120 },
    /* 279 - CLOCK_GetPLL0InClockRate */
    { &instanceList[279], &reviseItems[1760], 0x2c2f0, 0x1400, 52 },
    /* 280 - CLOCK_SetPLL0Freq */
    { &instanceList[280], &reviseItems[1765], 0x2c324, 0x1000, 200 },
    /* 281 - SDK_DelayAtLeastUs */
    { &instanceList[281], &reviseItems[1769], 0x2c3ec, 0xc00, 80 },
    /* 282 - DMA_GetInstance */
    { &instanceList[282], &reviseItems[1772], 0x2c43c, 0x800, 48 },
    /* 283 - DMA_Init */
    { &instanceList[283], &reviseItems[1774], 0x2c46c, 0x1000, 100 },
    /* 284 - DMA_SetupDescriptor */
    { &instanceList[284], &reviseItems[1778], 0x2c4d0, 0x800, 132 },
    /* 285 - DMA_CreateDescriptor */
    { &instanceList[285], &reviseItems[1780], 0x2c554, 0x800, 240 },
    /* 286 - DMA_CreateHandle */
    { &instanceList[286], &reviseItems[1782], 0x2c644, 0x1000, 128 },
    /* 287 - DMA_SetCallback */
    { &instanceList[287], &reviseItems[1786], 0x2c6c4, 0x800, 28 },
    /* 288 - DMA_PrepareTransfer */
    { &instanceList[288], &reviseItems[1788], 0x2c6e0, 0xc00, 192 },
    /* 289 - DMA_SubmitTransfer */
    { &instanceList[289], &reviseItems[1791], 0x2c7a0, 0x1000, 164 },
    /* 290 - DMA_StartTransfer */
    { &instanceList[290], &reviseItems[1795], 0x2c844, 0x800, 80 },
    /* 291 - DMA_IRQHandle */
    { &instanceList[291], &reviseItems[1797], 0x2c894, 0x1400, 212 },
    /* 292 - DMA0_DriverIRQHandler */
    { &instanceList[292], &reviseItems[1802], 0x2c968, 0x400, 12 },
    /* 293 - DMA1_DriverIRQHandler */
    { &instanceList[293], &reviseItems[1803], 0x2c974, 0x400, 12 },
    /* 294 - FLEXCOMM_GetInstance */
    { &instanceList[294], &reviseItems[1804], 0x2c980, 0x800, 48 },
    /* 295 - FLEXCOMM_Init */
    { &instanceList[295], &reviseItems[1806], 0x2c9b0, 0xc00, 136 },
    /* 296 - FLEXCOMM_SetIRQHandler */
    { &instanceList[296], &reviseItems[1809], 0x2ca38, 0x800, 40 },
    /* 297 - FLEXCOMM0_DriverIRQHandler */
    { &instanceList[297], &reviseItems[1811], 0x2ca60, 0x800, 52 },
    /* 298 - FLEXCOMM1_DriverIRQHandler */
    { &instanceList[298], &reviseItems[1813], 0x2ca94, 0x800, 52 },
    /* 299 - FLEXCOMM2_DriverIRQHandler */
    { &instanceList[299], &reviseItems[1815], 0x2cac8, 0x800, 52 },
    /* 300 - FLEXCOMM3_DriverIRQHandler */
    { &instanceList[300], &reviseItems[1817], 0x2cafc, 0x800, 52 },
    /* 301 - FLEXCOMM4_DriverIRQHandler */
    { &instanceList[301], &reviseItems[1819], 0x2cb30, 0x800, 52 },
    /* 302 - FLEXCOMM5_DriverIRQHandler */
    { &instanceList[302], &reviseItems[1821], 0x2cb64, 0x800, 52 },
    /* 303 - FLEXCOMM6_DriverIRQHandler */
    { &instanceList[303], &reviseItems[1823], 0x2cb98, 0x800, 52 },
    /* 304 - FLEXCOMM7_DriverIRQHandler */
    { &instanceList[304], &reviseItems[1825], 0x2cbcc, 0x800, 52 },
    /* 305 - FLEXCOMM8_DriverIRQHandler */
    { &instanceList[305], &reviseItems[1827], 0x2cc00, 0x800, 52 },
    /* 306 - __NVIC_EnableIRQ */
    { &instanceList[306], &reviseItems[1829], 0x2cc34, 0x400, 32 },
    /* 307 - __NVIC_ClearPendingIRQ */
    { &instanceList[307], &reviseItems[1830], 0x2cc54, 0x400, 32 },
    /* 308 - PINT_Init */
    { &instanceList[308], &reviseItems[1831], 0x2cc74, 0xc00, 144 },
    /* 309 - PINT_PinInterruptConfig */
    { &instanceList[309], &reviseItems[1834], 0x2cd04, 0x800, 96 },
    /* 310 - PINT_EnableCallback */
    { &instanceList[310], &reviseItems[1836], 0x2cd64, 0x2c00, 156 },
    /* 311 - SEC_GPIO_INT0_IRQ0_DriverIRQHandler */
    { &instanceList[311], &reviseItems[1847], 0x2ce00, 0x1000, 64 },
    /* 312 - SEC_GPIO_INT0_IRQ1_DriverIRQHandler */
    { &instanceList[312], &reviseItems[1851], 0x2ce40, 0x1000, 64 },
    /* 313 - PIN_INT0_DriverIRQHandler */
    { &instanceList[313], &reviseItems[1855], 0x2ce80, 0x1000, 64 },
    /* 314 - PIN_INT1_DriverIRQHandler */
    { &instanceList[314], &reviseItems[1859], 0x2cec0, 0x1000, 64 },
    /* 315 - PIN_INT2_DriverIRQHandler */
    { &instanceList[315], &reviseItems[1863], 0x2cf00, 0x1000, 64 },
    /* 316 - PIN_INT3_DriverIRQHandler */
    { &instanceList[316], &reviseItems[1867], 0x2cf40, 0x1000, 64 },
    /* 317 - PIN_INT4_DriverIRQHandler */
    { &instanceList[317], &reviseItems[1871], 0x2cf80, 0x1000, 64 },
    /* 318 - PIN_INT5_DriverIRQHandler */
    { &instanceList[318], &reviseItems[1875], 0x2cfc0, 0x1000, 64 },
    /* 319 - PIN_INT6_DriverIRQHandler */
    { &instanceList[319], &reviseItems[1879], 0x2d000, 0x1000, 64 },
    /* 320 - PIN_INT7_DriverIRQHandler */
    { &instanceList[320], &reviseItems[1883], 0x2d040, 0x1000, 64 },
    /* 321 - RESET_SetPeripheralReset */
    { &instanceList[321], &reviseItems[1887], 0x2d080, 0x800, 60 },
    /* 322 - RESET_ClearPeripheralReset */
    { &instanceList[322], &reviseItems[1889], 0x2d0bc, 0x800, 60 },
    /* 323 - SPI_GetInstance */
    { &instanceList[323], &reviseItems[1891], 0x2d0f8, 0x800, 48 },
    /* 324 - SPI_MasterTransferHandleIRQ */
    { &instanceList[324], &reviseItems[1893], 0x2d128, 0x1000, 584 },
    /* 325 - SPI_SetDummyData */
    { &instanceList[325], &reviseItems[1897], 0x2d370, 0x800, 28 },
    /* 326 - SPI_GetConfig */
    { &instanceList[326], &reviseItems[1899], 0x2d38c, 0x800, 28 },
    /* 327 - SPI_MasterGetDefaultConfig */
    { &instanceList[327], &reviseItems[1901], 0x2d3a8, 0xc00, 64 },
    /* 328 - SPI_MasterSetBaud */
    { &instanceList[328], &reviseItems[1904], 0x2d3e8, 0x800, 80 },
    /* 329 - SPI_MasterInit */
    { &instanceList[329], &reviseItems[1906], 0x2d438, 0x1800, 304 },
    /* 330 - SPI_MasterTransferCreateHandle */
    { &instanceList[330], &reviseItems[1912], 0x2d568, 0x1400, 192 },
    /* 331 - SPI_MasterTransferNonBlocking */
    { &instanceList[331], &reviseItems[1917], 0x2d628, 0x800, 152 },
    /* 332 - SPI_MasterTransferCreateHandleDMA */
    { &instanceList[332], &reviseItems[1919], 0x2d6c0, 0x1800, 148 },
    /* 333 - SPI_MasterTransferDMA */
    { &instanceList[333], &reviseItems[1925], 0x2d754, 0x6c00, 880 },
    /* 334 - USART_GetDefaultConfig */
    { &instanceList[334], &reviseItems[1952], 0x2dac4, 0xc00, 56 },
    /* 335 - USART_SetBaudRate */
    { &instanceList[335], &reviseItems[1955], 0x2dafc, 0x800, 156 },
    /* 336 - USART_Init */
    { &instanceList[336], &reviseItems[1957], 0x2db98, 0x1000, 312 },
    /* 337 - USART_WriteBlocking */
    { &instanceList[337], &reviseItems[1961], 0x2dcd0, 0x800, 72 },
    /* 338 - HAL_UartInit */
    { &instanceList[338], &reviseItems[1963], 0x2dd18, 0x1000, 184 },
    /* 339 - HAL_UartSendBlocking */
    { &instanceList[339], &reviseItems[1967], 0x2ddd0, 0xc00, 68 },
    /* 340 - SerialManager_Init */
    { &instanceList[340], &reviseItems[1970], 0x2de14, 0x1000, 76 },
    /* 341 - SerialManager_OpenWriteHandle */
    { &instanceList[341], &reviseItems[1974], 0x2de60, 0xc00, 72 },
    /* 342 - SerialManager_OpenReadHandle */
    { &instanceList[342], &reviseItems[1977], 0x2dea8, 0xc00, 84 },
    /* 343 - SerialManager_WriteBlocking */
    { &instanceList[343], &reviseItems[1980], 0x2defc, 0xc00, 76 },
    /* 344 - Serial_UartInit */
    { &instanceList[344], &reviseItems[1983], 0x2df48, 0xc00, 88 },
    /* 345 - Serial_UartWrite */
    { &instanceList[345], &reviseItems[1986], 0x2dfa0, 0x800, 48 },
    /* 346 - BOARD_InitDebugConsole */
    { &instanceList[346], &reviseItems[1988], 0x2dfd0, 0xc00, 52 },
    /* 347 - BOARD_BootClockPLL150M */
    { &instanceList[347], &reviseItems[1991], 0x2e004, 0x5000, 392 },
    /* 348 - BOARD_InitSilex2401Shield */
    { &instanceList[348], &reviseItems[2011], 0x2e18c, 0x1000, 228 },
    /* 349 - lowpower_set_system_voltage */
    { &instanceList[349], &reviseItems[2015], 0x2e270, 0x400, 164 },
    /* 350 - lowpower_set_voltage_for_process */
    { &instanceList[350], &reviseItems[2016], 0x2e314, 0x400, 132 },
    /* 351 - POWER_SetVoltageForFreq */
    { &instanceList[351], &reviseItems[2017], 0x2e398, 0x400, 132 },
    /* 352 - __assertion_failed */
    { &instanceList[352], &reviseItems[2018], 0x2e41c, 0x1000, 88 },
    /* 353 - _Cwritebuf */
    { &instanceList[353], &reviseItems[2022], 0x2e474, 0x1000, 124 },
    /* 354 - malloc */
    { &instanceList[354], &reviseItems[2026], 0x2e4f0, 0xc00, 212 },
    /* 355 - _Csys_alloc */
    { &instanceList[355], &reviseItems[2029], 0x2e5c4, 0x1000, 48 },
    /* 356 - fseek */
    { &instanceList[356], &reviseItems[2033], 0x2e5f4, 0x1000, 272 },
    /* 357 - ftell */
    { &instanceList[357], &reviseItems[2037], 0x2e704, 0x1000, 76 },
    /* 358 - _initio */
    { &instanceList[358], &reviseItems[2041], 0x2e750, 0x1c00, 144 },
    /* 359 - modf */
    { &instanceList[359], &reviseItems[2048], 0x2e7e0, 0xc00, 152 },
    /* 360 - __vfprintf */
    { &instanceList[360], &reviseItems[2051], 0x2e878, 0x5000, 3188 },
    /* 361 - _sprintf */
    { &instanceList[361], &reviseItems[2071], 0x2f4ec, 0x1000, 120 },
    /* 362 - _snprintf */
    { &instanceList[362], &reviseItems[2075], 0x2f564, 0x1000, 132 },
    /* 363 - _vsnprintf */
    { &instanceList[363], &reviseItems[2079], 0x2f5e8, 0x1000, 120 },
    /* 364 - _printf */
    { &instanceList[364], &reviseItems[2083], 0x2f660, 0x1800, 108 },
    /* 365 - ch_val */
    { &instanceList[365], &reviseItems[2089], 0x2f6cc, 0x400, 52 },
    /* 366 - cr_rd_int */
    { &instanceList[366], &reviseItems[2090], 0x2f700, 0x2000, 456 },
    /* 367 - __filbuf */
    { &instanceList[367], &reviseItems[2098], 0x2f8c8, 0x2000, 408 },
    /* 368 - _sbrk */
    { &instanceList[368], &reviseItems[2106], 0x2fa60, 0x800, 68 },
    /* 369 - fflush */
    { &instanceList[369], &reviseItems[2108], 0x2faa4, 0xc00, 76 },
    /* 370 - __check_heap_overflow */
    { &instanceList[370], &reviseItems[2111], 0x2faf0, 0x800, 28 },
    /* 371 - __aeabi_dmul */
    { &instanceList[371], &reviseItems[2113], 0x2fb0c, 0x400, 280 },
    /* 372 - __aeabi_ddiv */
    { &instanceList[372], &reviseItems[2114], 0x2fc24, 0x400, 336 },
    /* 373 - __aeabi_dsub */
    { &instanceList[373], &reviseItems[2115], 0x2fd74, 0x800, 436 },
    /* 374 - __aeabi_dadd */
    { &instanceList[374], &reviseItems[2117], 0x2ff28, 0x800, 280 },
    /* 375 - __aeabi_d2f */
    { &instanceList[375], &reviseItems[2119], 0x30040, 0x400, 92 },
    /* 376 - __aeabi_f2d */
    { &instanceList[376], &reviseItems[2120], 0x3009c, 0x800, 60 },
    /* 377 - a_free */
    { &instanceList[377], &reviseItems[2122], 0x300d8, 0x400, 4 },
    /* 378 - a_is_mutex_valid */
    { &instanceList[378], &reviseItems[2123], 0x300dc, 0x400, 6 },
    /* 379 - SPI_MasterUserCallback */
    { &instanceList[379], &reviseItems[2124], 0x300e2, 0x400, 4 },
    /* 380 - WIFISHIELD_DeinitDrivers */
    { &instanceList[380], &reviseItems[2125], 0x300e6, 0x400, 6 },
    /* 381 - WIFISHIELD_NotifyDriverTask */
    { &instanceList[381], &reviseItems[2126], 0x300ec, 0xc00, 28 },
    /* 382 - PINT_callback */
    { &instanceList[382], &reviseItems[2129], 0x30108, 0x400, 6 },
    /* 383 - t_socket */
    { &instanceList[383], &reviseItems[2130], 0x3010e, 0x1000, 146 },
    /* 384 - t_connect */
    { &instanceList[384], &reviseItems[2134], 0x301a0, 0xc00, 58 },
    /* 385 - t_ipconfig */
    { &instanceList[385], &reviseItems[2137], 0x301da, 0xc00, 82 },
    /* 386 - Custom_Api_Http_Post_Event */
    { &instanceList[386], &reviseItems[2140], 0x3022c, 0x1000, 58 },
    /* 387 - Custom_Api_Ota_Resp_Result */
    { &instanceList[387], &reviseItems[2144], 0x30266, 0x1000, 64 },
    /* 388 - t_recvfrom */
    { &instanceList[388], &reviseItems[2148], 0x302a6, 0xc00, 78 },
    /* 389 - t_recv */
    { &instanceList[389], &reviseItems[2151], 0x302f4, 0x800, 28 },
    /* 390 - txpkt_free */
    { &instanceList[390], &reviseItems[2153], 0x30310, 0x800, 26 },
    /* 391 - custom_alloc */
    { &instanceList[391], &reviseItems[2155], 0x3032a, 0x1000, 74 },
    /* 392 - Custom_Api_Send */
    { &instanceList[392], &reviseItems[2159], 0x30374, 0x400, 6 },
    /* 393 - custom_sock_is_pending */
    { &instanceList[393], &reviseItems[2160], 0x3037a, 0x400, 14 },
    /* 394 - Custom_DeliverFrameToNetworkStack */
    { &instanceList[394], &reviseItems[2161], 0x30388, 0x800, 32 },
    /* 395 - custom_send_tcpip */
    { &instanceList[395], &reviseItems[2163], 0x303a8, 0x1800, 94 },
    /* 396 - Custom_FreeRxRequest */
    { &instanceList[396], &reviseItems[2169], 0x30406, 0x400, 4 },
    /* 397 - a_netbuf_dequeue_adv */
    { &instanceList[397], &reviseItems[2170], 0x3040a, 0x400, 70 },
    /* 398 - a_netbuf_init */
    { &instanceList[398], &reviseItems[2171], 0x30450, 0x400, 30 },
    /* 399 - a_netbuf_alloc */
    { &instanceList[399], &reviseItems[2172], 0x3046e, 0x1800, 112 },
    /* 400 - a_netbuf_reinit */
    { &instanceList[400], &reviseItems[2178], 0x304de, 0x800, 48 },
    /* 401 - a_netbuf_set_rx_pool */
    { &instanceList[401], &reviseItems[2180], 0x3050e, 0x400, 10 },
    /* 402 - a_netbuf_alloc_raw */
    { &instanceList[402], &reviseItems[2181], 0x30518, 0x1800, 104 },
    /* 403 - a_netbuf_to_len */
    { &instanceList[403], &reviseItems[2187], 0x30580, 0x400, 50 },
    /* 404 - a_netbuf_get_fragment */
    { &instanceList[404], &reviseItems[2188], 0x305b2, 0x400, 56 },
    /* 405 - a_netbuf_enqueue */
    { &instanceList[405], &reviseItems[2189], 0x305ea, 0x800, 50 },
    /* 406 - a_netbuf_free_rx_pool */
    { &instanceList[406], &reviseItems[2191], 0x3061c, 0x1000, 56 },
    /* 407 - a_netbuf_free */
    { &instanceList[407], &reviseItems[2195], 0x30654, 0x1400, 68 },
    /* 408 - a_netbuf_dequeue */
    { &instanceList[408], &reviseItems[2200], 0x30698, 0xc00, 66 },
    /* 409 - a_netbuf_queue_init */
    { &instanceList[409], &reviseItems[2203], 0x306da, 0x400, 12 },
    /* 410 - a_netbuf_configure */
    { &instanceList[410], &reviseItems[2204], 0x306e6, 0x800, 50 },
    /* 411 - a_netbuf_to_data */
    { &instanceList[411], &reviseItems[2206], 0x30718, 0x400, 6 },
    /* 412 - a_netbuf_put_data */
    { &instanceList[412], &reviseItems[2207], 0x3071e, 0xc00, 42 },
    /* 413 - a_netbuf_headroom */
    { &instanceList[413], &reviseItems[2210], 0x30748, 0x400, 10 },
    /* 414 - a_netbuf_tailroom */
    { &instanceList[414], &reviseItems[2211], 0x30752, 0x400, 10 },
    /* 415 - Custom_Api_Shutdown */
    { &instanceList[415], &reviseItems[2212], 0x3075c, 0x800, 20 },
    /* 416 - chip_state_ctrl */
    { &instanceList[416], &reviseItems[2214], 0x30770, 0xc00, 38 },
    /* 417 - config_dump_target_assert_info */
    { &instanceList[417], &reviseItems[2217], 0x30796, 0x800, 56 },
    /* 418 - fill_ext_scan_info */
    { &instanceList[418], &reviseItems[2219], 0x307ce, 0x1400, 314 },
    /* 419 - fill_scan_info */
    { &instanceList[419], &reviseItems[2224], 0x30908, 0x1000, 300 },
    /* 420 - Custom_Api_BssInfoEvent */
    { &instanceList[420], &reviseItems[2228], 0x30a34, 0x1c00, 332 },
    /* 421 - Custom_Api_ConnectEvent */
    { &instanceList[421], &reviseItems[2235], 0x30b80, 0x1800, 100 },
    /* 422 - Custom_Api_ReadyEvent */
    { &instanceList[422], &reviseItems[2241], 0x30be4, 0x800, 28 },
    /* 423 - Custom_Api_RSNASuccessEvent */
    { &instanceList[423], &reviseItems[2243], 0x30c00, 0x1000, 62 },
    /* 424 - Custom_Api_ProbeReq_Event */
    { &instanceList[424], &reviseItems[2247], 0x30c3e, 0x1000, 80 },
    /* 425 - wmi_qos_state_init */
    { &instanceList[425], &reviseItems[2251], 0x30c8e, 0xc00, 46 },
    /* 426 - wmi_init */
    { &instanceList[426], &reviseItems[2254], 0x30cbc, 0x1400, 64 },
    /* 427 - wmi_shutdown */
    { &instanceList[427], &reviseItems[2259], 0x30cfc, 0x1000, 50 },
    /* 428 - wmi_control_rx_xtnd */
    { &instanceList[428], &reviseItems[2263], 0x30d2e, 0x2c00, 224 },
    /* 429 - wmi_storerecall_recall_cmd */
    { &instanceList[429], &reviseItems[2274], 0x30e0e, 0x1800, 104 },
    /* 430 - wmi_sdpd_send_cmd */
    { &instanceList[430], &reviseItems[2280], 0x30e76, 0x2000, 120 },
    /* 431 - wmi_p2p_set_oppps */
    { &instanceList[431], &reviseItems[2288], 0x30eee, 0x1400, 74 },
    /* 432 - wmi_p2p_set_noa */
    { &instanceList[432], &reviseItems[2293], 0x30f38, 0x1c00, 138 },
    /* 433 - wmi_cmd_start */
    { &instanceList[433], &reviseItems[2300], 0x30fc2, 0x1800, 86 },
    /* 434 - wmi_ap_set_param */
    { &instanceList[434], &reviseItems[2306], 0x31018, 0x1800, 188 },
    /* 435 - wmi_bssfilter_cmd */
    { &instanceList[435], &reviseItems[2312], 0x310d4, 0x800, 42 },
    /* 436 - wmi_dset_host_cfg_cmd */
    { &instanceList[436], &reviseItems[2314], 0x310fe, 0xc00, 136 },
    /* 437 - wmi_set_appie_cmd */
    { &instanceList[437], &reviseItems[2317], 0x31186, 0x1c00, 110 },
    /* 438 - Util_GetEndpoint */
    { &instanceList[438], &reviseItems[2324], 0x311f4, 0x400, 18 },
    /* 439 - Util_Freq2ieee */
    { &instanceList[439], &reviseItems[2325], 0x31206, 0xc00, 74 },
    /* 440 - Util_AC2EndpointID */
    { &instanceList[440], &reviseItems[2328], 0x31250, 0x400, 12 },
    /* 441 - dset_get */
    { &instanceList[441], &reviseItems[2329], 0x3125c, 0x1400, 82 },
    /* 442 - dset_write */
    { &instanceList[442], &reviseItems[2334], 0x312ae, 0x800, 38 },
    /* 443 - dset_read */
    { &instanceList[443], &reviseItems[2336], 0x312d4, 0x800, 42 },
    /* 444 - SOCK_EV_MASK_TEST */
    { &instanceList[444], &reviseItems[2338], 0x312fe, 0x400, 30 },
    /* 445 - unblock */
    { &instanceList[445], &reviseItems[2339], 0x3131c, 0x800, 48 },
    /* 446 - unblockSelect */
    { &instanceList[446], &reviseItems[2341], 0x3134c, 0x800, 22 },
    /* 447 - aggr_deinit */
    { &instanceList[447], &reviseItems[2343], 0x31362, 0x400, 4 },
    /* 448 - qcom_set_deviceid */
    { &instanceList[448], &reviseItems[2344], 0x31366, 0x800, 42 },
    /* 449 - qcom_socket */
    { &instanceList[449], &reviseItems[2346], 0x31390, 0x800, 34 },
    /* 450 - qcom_connect */
    { &instanceList[450], &reviseItems[2348], 0x313b2, 0x800, 32 },
    /* 451 - qcom_recv */
    { &instanceList[451], &reviseItems[2350], 0x313d2, 0xc00, 44 },
    /* 452 - qcom_send */
    { &instanceList[452], &reviseItems[2353], 0x313fe, 0xc00, 44 },
    /* 453 - qcom_ipconfig */
    { &instanceList[453], &reviseItems[2356], 0x3142a, 0x1000, 72 },
    /* 454 - qcom_dhcpc_register_cb */
    { &instanceList[454], &reviseItems[2360], 0x31472, 0x1000, 46 },
    /* 455 - qcom_set_ssid */
    { &instanceList[455], &reviseItems[2364], 0x314a0, 0xc00, 68 },
    /* 456 - qcom_get_ssid */
    { &instanceList[456], &reviseItems[2367], 0x314e4, 0xc00, 76 },
    /* 457 - qcom_set_connect_callback */
    { &instanceList[457], &reviseItems[2370], 0x31530, 0xc00, 68 },
    /* 458 - qcom_commit */
    { &instanceList[458], &reviseItems[2373], 0x31574, 0x1400, 70 },
    /* 459 - qcom_op_get_mode */
    { &instanceList[459], &reviseItems[2378], 0x315ba, 0xc00, 56 },
    /* 460 - qcom_op_set_mode */
    { &instanceList[460], &reviseItems[2381], 0x315f2, 0xc00, 58 },
    /* 461 - qcom_disconnect */
    { &instanceList[461], &reviseItems[2384], 0x3162c, 0x1400, 82 },
    /* 462 - qcom_set_channel */
    { &instanceList[462], &reviseItems[2389], 0x3167e, 0xc00, 108 },
    /* 463 - qcom_sec_set_auth_mode */
    { &instanceList[463], &reviseItems[2392], 0x316ea, 0xc00, 56 },
    /* 464 - qcom_sec_set_encrypt_mode */
    { &instanceList[464], &reviseItems[2395], 0x31722, 0xc00, 90 },
    /* 465 - qcom_sec_set_passphrase */
    { &instanceList[465], &reviseItems[2398], 0x3177c, 0x1000, 88 },
    /* 466 - qcom_power_set_mode */
    { &instanceList[466], &reviseItems[2402], 0x317d4, 0xc00, 76 },
    /* 467 - qcom_get_bssid */
    { &instanceList[467], &reviseItems[2405], 0x31820, 0x800, 42 },
    /* 468 - HW_ProcessPendingInterrupts */
    { &instanceList[468], &reviseItems[2407], 0x3184a, 0x1c00, 168 },
    /* 469 - HW_InterruptHandler */
    { &instanceList[469], &reviseItems[2414], 0x318f2, 0xc00, 40 },
    /* 470 - HW_SetClock */
    { &instanceList[470], &reviseItems[2417], 0x3191a, 0x400, 4 },
    /* 471 - Htc_DistributeCredits */
    { &instanceList[471], &reviseItems[2418], 0x3191e, 0x400, 58 },
    /* 472 - Htc_PrepareRecvPacket */
    { &instanceList[472], &reviseItems[2419], 0x31958, 0x800, 72 },
    /* 473 - Htc_GetCreditCounterUpdate */
    { &instanceList[473], &reviseItems[2421], 0x319a0, 0xc00, 88 },
    /* 474 - Htc_ProcessTxComplete */
    { &instanceList[474], &reviseItems[2424], 0x319f8, 0x400, 8 },
    /* 475 - DoPioReadInternal.isra.0 */
    { &instanceList[475], &reviseItems[2425], 0x31a00, 0x800, 50 },
    /* 476 - DoPioWriteInternal */
    { &instanceList[476], &reviseItems[2427], 0x31a32, 0x800, 40 },
    /* 477 - Hcd_DoPioInternalAccess */
    { &instanceList[477], &reviseItems[2429], 0x31a5a, 0x800, 30 },
    /* 478 - Hcd_RefreshWriteBufferSpace */
    { &instanceList[478], &reviseItems[2431], 0x31a78, 0x800, 36 },
    /* 479 - Hcd_UnmaskInterrupts */
    { &instanceList[479], &reviseItems[2433], 0x31a9c, 0x800, 44 },
    /* 480 - MaskSPIInterrupts */
    { &instanceList[480], &reviseItems[2435], 0x31ac8, 0x800, 48 },
    /* 481 - Hcd_ReinitTarget */
    { &instanceList[481], &reviseItems[2437], 0x31af8, 0x1400, 70 },
    /* 482 - Hcd_Deinitialize */
    { &instanceList[482], &reviseItems[2442], 0x31b3e, 0x800, 26 },
    /* 483 - HW_EnableDisableSPIIRQ */
    { &instanceList[483], &reviseItems[2444], 0x31b58, 0x1400, 84 },
    /* 484 - DoDMAOp */
    { &instanceList[484], &reviseItems[2449], 0x31bac, 0x1c00, 182 },
    /* 485 - Bus_InOutToken */
    { &instanceList[485], &reviseItems[2456], 0x31c62, 0x800, 32 },
    /* 486 - HW_EnableDisableIRQ */
    { &instanceList[486], &reviseItems[2458], 0x31c82, 0x400, 4 },
    /* 487 - Driver_SetAddressWindowRegister */
    { &instanceList[487], &reviseItems[2459], 0x31c86, 0x1400, 158 },
    /* 488 - Driver_ReadDataDiag */
    { &instanceList[488], &reviseItems[2464], 0x31d24, 0x800, 54 },
    /* 489 - Driver_WriteDataDiag */
    { &instanceList[489], &reviseItems[2466], 0x31d5a, 0x800, 54 },
    /* 490 - ConnectService */
    { &instanceList[490], &reviseItems[2468], 0x31d90, 0x1000, 158 },
    /* 491 - Driver_DropTxDataPackets */
    { &instanceList[491], &reviseItems[2472], 0x31e2e, 0x2400, 154 },
    /* 492 - Driver_WaitForCondition */
    { &instanceList[492], &reviseItems[2481], 0x31ec8, 0xc00, 78 },
    /* 493 - setup_host_dset */
    { &instanceList[493], &reviseItems[2484], 0x31f16, 0x400, 4 },
    /* 494 - Driver_WakeDriver */
    { &instanceList[494], &reviseItems[2485], 0x31f1a, 0x400, 8 },
    /* 495 - Driver_ReportRxBuffStatus */
    { &instanceList[495], &reviseItems[2486], 0x31f22, 0x800, 26 },
    /* 496 - Driver_DestroyThread */
    { &instanceList[496], &reviseItems[2488], 0x31f3c, 0x800, 26 },
    /* 497 - Driver_WakeUser */
    { &instanceList[497], &reviseItems[2490], 0x31f56, 0x400, 8 },
    /* 498 - Atheros_Driver_Task */
    { &instanceList[498], &reviseItems[2491], 0x31f5e, 0x1800, 152 },
    /* 499 - Driver_PostProcessRequest */
    { &instanceList[499], &reviseItems[2497], 0x31ff6, 0x400, 36 },
    /* 500 - Driver_TxComplete */
    { &instanceList[500], &reviseItems[2498], 0x3201a, 0x800, 26 },
    /* 501 - Driver_SendPacket */
    { &instanceList[501], &reviseItems[2500], 0x32034, 0x1800, 106 },
    /* 502 - Driver_RecvPacket */
    { &instanceList[502], &reviseItems[2506], 0x3209e, 0x1800, 84 },
    /* 503 - Api_InitStart */
    { &instanceList[503], &reviseItems[2512], 0x320f2, 0xc00, 26 },
    /* 504 - Install_static_wep_keys */
    { &instanceList[504], &reviseItems[2515], 0x3210c, 0x1000, 160 },
    /* 505 - Api_DisconnectWiFi */
    { &instanceList[505], &reviseItems[2519], 0x321ac, 0xc00, 130 },
    /* 506 - Api_ConnectWiFi */
    { &instanceList[506], &reviseItems[2522], 0x3222e, 0x2c00, 502 },
    /* 507 - Api_DriverAccessCheck */
    { &instanceList[507], &reviseItems[2533], 0x32424, 0xc00, 124 },
    /* 508 - Api_SetPowerMode */
    { &instanceList[508], &reviseItems[2536], 0x324a0, 0x800, 112 },
    /* 509 - wait_scan_done */
    { &instanceList[509], &reviseItems[2538], 0x32510, 0xc00, 66 },
    /* 510 - scan_setup */
    { &instanceList[510], &reviseItems[2541], 0x32552, 0x1c00, 242 },
    /* 511 - Util_Ascii2Hex */
    { &instanceList[511], &reviseItems[2548], 0x32644, 0x400, 44 },
    /* 512 - TxRawPacket */
    { &instanceList[512], &reviseItems[2549], 0x32670, 0x2000, 156 },
    /* 513 - query_credit_deficit */
    { &instanceList[513], &reviseItems[2557], 0x3270c, 0xc00, 56 },
    /* 514 - Api_WmiTxStart */
    { &instanceList[514], &reviseItems[2560], 0x32744, 0x800, 28 },
    /* 515 - Api_DataTxStart */
    { &instanceList[515], &reviseItems[2562], 0x32760, 0x1c00, 196 },
    /* 516 - Api_TargetStatsEvent */
    { &instanceList[516], &reviseItems[2569], 0x32824, 0x400, 24 },
    /* 517 - Api_RegDomainEvent */
    { &instanceList[517], &reviseItems[2570], 0x3283c, 0x400, 10 },
    /* 518 - Api_GetBitRateEvent */
    { &instanceList[518], &reviseItems[2571], 0x32846, 0x400, 8 },
    /* 519 - Api_ChannelListEvent */
    { &instanceList[519], &reviseItems[2572], 0x3284e, 0x800, 50 },
    /* 520 - Api_ScanCompleteEvent */
    { &instanceList[520], &reviseItems[2574], 0x32880, 0xc00, 50 },
    /* 521 - Api_BssInfoEvent */
    { &instanceList[521], &reviseItems[2577], 0x328b2, 0x400, 8 },
    /* 522 - Api_TkipMicErrorEvent */
    { &instanceList[522], &reviseItems[2578], 0x328ba, 0xc00, 56 },
    /* 523 - Api_GetPmkEvent */
    { &instanceList[523], &reviseItems[2581], 0x328f2, 0x800, 50 },
    /* 524 - Api_ConnectEvent */
    { &instanceList[524], &reviseItems[2583], 0x32924, 0x2800, 338 },
    /* 525 - Api_DisconnectEvent */
    { &instanceList[525], &reviseItems[2593], 0x32a76, 0x2800, 242 },
    /* 526 - Api_dset_read_event */
    { &instanceList[526], &reviseItems[2603], 0x32b68, 0xc00, 152 },
    /* 527 - Api_StoreRecallEvent */
    { &instanceList[527], &reviseItems[2606], 0x32c00, 0x1000, 124 },
    /* 528 - Api_StoreRecallStartEvent */
    { &instanceList[528], &reviseItems[2610], 0x32c7c, 0x800, 58 },
    /* 529 - Api_WpsProfileEvent */
    { &instanceList[529], &reviseItems[2612], 0x32cb6, 0x1000, 74 },
    /* 530 - Api_AggrRecvAddbaReqEvent */
    { &instanceList[530], &reviseItems[2616], 0x32d00, 0x800, 42 },
    /* 531 - Api_AggrRecvDelbaReqEvent */
    { &instanceList[531], &reviseItems[2618], 0x32d2a, 0x400, 12 },
    /* 532 - Api_RSNASuccessEvent */
    { &instanceList[532], &reviseItems[2619], 0x32d36, 0x400, 4 },
    /* 533 - Api_GetTemperatureReply */
    { &instanceList[533], &reviseItems[2620], 0x32d3a, 0x400, 48 },
    /* 534 - Api_GetWpsInitReply */
    { &instanceList[534], &reviseItems[2621], 0x32d6a, 0x400, 36 },
    /* 535 - Api_GetCountryCodeReply */
    { &instanceList[535], &reviseItems[2622], 0x32d8e, 0x800, 36 },
    /* 536 - Api_GetSetParamReply */
    { &instanceList[536], &reviseItems[2624], 0x32db2, 0x400, 20 },
    /* 537 - Api_RxDbglogEvent */
    { &instanceList[537], &reviseItems[2625], 0x32dc6, 0x400, 4 },
    /* 538 - Api_RxGpioDataEvent */
    { &instanceList[538], &reviseItems[2626], 0x32dca, 0x400, 8 },
    /* 539 - Api_RxHBChallengeEvent */
    { &instanceList[539], &reviseItems[2627], 0x32dd2, 0x400, 46 },
    /* 540 - Api_RxPfmDataEvent */
    { &instanceList[540], &reviseItems[2628], 0x32e00, 0x400, 8 },
    /* 541 - Api_RxPfmDataDoneEvent */
    { &instanceList[541], &reviseItems[2629], 0x32e08, 0x400, 8 },
    /* 542 - Api_p2p_go_neg_event */
    { &instanceList[542], &reviseItems[2630], 0x32e10, 0x1c00, 136 },
    /* 543 - p2p_go_neg_event */
    { &instanceList[543], &reviseItems[2637], 0x32e98, 0x400, 4 },
    /* 544 - Api_p2p_node_list_event */
    { &instanceList[544], &reviseItems[2638], 0x32e9c, 0x1c00, 132 },
    /* 545 - p2p_node_list_event */
    { &instanceList[545], &reviseItems[2645], 0x32f20, 0x400, 4 },
    /* 546 - Api_p2p_req_auth_event */
    { &instanceList[546], &reviseItems[2646], 0x32f24, 0x1c00, 122 },
    /* 547 - p2p_req_auth_event */
    { &instanceList[547], &reviseItems[2653], 0x32f9e, 0x400, 4 },
    /* 548 - Api_p2p_list_persistent_network_event */
    { &instanceList[548], &reviseItems[2654], 0x32fa2, 0x1c00, 124 },
    /* 549 - p2p_list_persistent_network_event */
    { &instanceList[549], &reviseItems[2661], 0x3301e, 0x400, 4 },
    /* 550 - Api_get_p2p_ctx */
    { &instanceList[550], &reviseItems[2662], 0x33022, 0x1c00, 122 },
    /* 551 - get_p2p_ctx */
    { &instanceList[551], &reviseItems[2669], 0x3309c, 0x400, 4 },
    /* 552 - Api_p2p_prov_disc_req */
    { &instanceList[552], &reviseItems[2670], 0x330a0, 0x1c00, 122 },
    /* 553 - get_p2p_prov_disc_req */
    { &instanceList[553], &reviseItems[2677], 0x3311a, 0x400, 4 },
    /* 554 - Api_p2p_serv_disc_req */
    { &instanceList[554], &reviseItems[2678], 0x3311e, 0x1c00, 122 },
    /* 555 - get_p2p_serv_disc_req */
    { &instanceList[555], &reviseItems[2685], 0x33198, 0x400, 4 },
    /* 556 - Api_p2p_invite_req */
    { &instanceList[556], &reviseItems[2686], 0x3319c, 0x1c00, 122 },
    /* 557 - p2p_invite_req_rx */
    { &instanceList[557], &reviseItems[2693], 0x33216, 0x400, 4 },
    /* 558 - Api_p2p_invite_rcvd_result */
    { &instanceList[558], &reviseItems[2694], 0x3321a, 0x1c00, 122 },
    /* 559 - p2p_invite_rcvd_result_ev */
    { &instanceList[559], &reviseItems[2701], 0x33294, 0x400, 4 },
    /* 560 - Api_p2p_invite_send_result */
    { &instanceList[560], &reviseItems[2702], 0x33298, 0x1c00, 122 },
    /* 561 - p2p_invite_sent_result_event */
    { &instanceList[561], &reviseItems[2709], 0x33312, 0x400, 4 },
    /* 562 - Api_Test_Cmd_Event */
    { &instanceList[562], &reviseItems[2710], 0x33316, 0x800, 32 },
    /* 563 - Api_TestCmdEventRx */
    { &instanceList[563], &reviseItems[2712], 0x33336, 0x800, 34 },
    /* 564 - Api_ProbeReqEvent */
    { &instanceList[564], &reviseItems[2714], 0x33358, 0x400, 4 },
    /* 565 - DbgConsole_PrintCallback */
    { &instanceList[565], &reviseItems[2715], 0x3335c, 0x800, 66 },
    /* 566 - PrintOutputdifFobpu.isra.0 */
    { &instanceList[566], &reviseItems[2717], 0x3339e, 0xc00, 60 },
    /* 567 - WDT_BOD_IRQHandler */
    { &instanceList[567], &reviseItems[2720], 0x333da, 0x442, 12 },
    /* 568 - DMA0_IRQHandler */
    { &instanceList[568], &reviseItems[2721], 0x333e6, 0x446, 12 },
    /* 569 - GINT0_IRQHandler */
    { &instanceList[569], &reviseItems[2722], 0x333f2, 0x44a, 12 },
    /* 570 - GINT1_IRQHandler */
    { &instanceList[570], &reviseItems[2723], 0x333fe, 0x44e, 12 },
    /* 571 - PIN_INT0_IRQHandler */
    { &instanceList[571], &reviseItems[2724], 0x3340a, 0x452, 12 },
    /* 572 - PIN_INT1_IRQHandler */
    { &instanceList[572], &reviseItems[2725], 0x33416, 0x456, 12 },
    /* 573 - PIN_INT2_IRQHandler */
    { &instanceList[573], &reviseItems[2726], 0x33422, 0x45a, 12 },
    /* 574 - PIN_INT3_IRQHandler */
    { &instanceList[574], &reviseItems[2727], 0x3342e, 0x45e, 12 },
    /* 575 - UTICK0_IRQHandler */
    { &instanceList[575], &reviseItems[2728], 0x3343a, 0x462, 12 },
    /* 576 - MRT0_IRQHandler */
    { &instanceList[576], &reviseItems[2729], 0x33446, 0x466, 12 },
    /* 577 - CTIMER0_IRQHandler */
    { &instanceList[577], &reviseItems[2730], 0x33452, 0x46a, 12 },
    /* 578 - CTIMER1_IRQHandler */
    { &instanceList[578], &reviseItems[2731], 0x3345e, 0x46e, 12 },
    /* 579 - SCT0_IRQHandler */
    { &instanceList[579], &reviseItems[2732], 0x3346a, 0x472, 12 },
    /* 580 - CTIMER3_IRQHandler */
    { &instanceList[580], &reviseItems[2733], 0x33476, 0x476, 12 },
    /* 581 - FLEXCOMM0_IRQHandler */
    { &instanceList[581], &reviseItems[2734], 0x33482, 0x47a, 12 },
    /* 582 - FLEXCOMM1_IRQHandler */
    { &instanceList[582], &reviseItems[2735], 0x3348e, 0x47e, 12 },
    /* 583 - FLEXCOMM2_IRQHandler */
    { &instanceList[583], &reviseItems[2736], 0x3349a, 0x482, 12 },
    /* 584 - FLEXCOMM3_IRQHandler */
    { &instanceList[584], &reviseItems[2737], 0x334a6, 0x486, 12 },
    /* 585 - FLEXCOMM4_IRQHandler */
    { &instanceList[585], &reviseItems[2738], 0x334b2, 0x48a, 12 },
    /* 586 - FLEXCOMM5_IRQHandler */
    { &instanceList[586], &reviseItems[2739], 0x334be, 0x48e, 12 },
    /* 587 - FLEXCOMM6_IRQHandler */
    { &instanceList[587], &reviseItems[2740], 0x334ca, 0x492, 12 },
    /* 588 - FLEXCOMM7_IRQHandler */
    { &instanceList[588], &reviseItems[2741], 0x334d6, 0x496, 12 },
    /* 589 - ADC0_IRQHandler */
    { &instanceList[589], &reviseItems[2742], 0x334e2, 0x49a, 12 },
    /* 590 - Reserved39_IRQHandler */
    { &instanceList[590], &reviseItems[2743], 0x334ee, 0x49e, 12 },
    /* 591 - ACMP_IRQHandler */
    { &instanceList[591], &reviseItems[2744], 0x334fa, 0x4a2, 12 },
    /* 592 - Reserved41_IRQHandler */
    { &instanceList[592], &reviseItems[2745], 0x33506, 0x4a6, 12 },
    /* 593 - Reserved42_IRQHandler */
    { &instanceList[593], &reviseItems[2746], 0x33512, 0x4aa, 12 },
    /* 594 - USB0_NEEDCLK_IRQHandler */
    { &instanceList[594], &reviseItems[2747], 0x3351e, 0x4ae, 12 },
    /* 595 - USB0_IRQHandler */
    { &instanceList[595], &reviseItems[2748], 0x3352a, 0x4b2, 12 },
    /* 596 - RTC_IRQHandler */
    { &instanceList[596], &reviseItems[2749], 0x33536, 0x4b6, 12 },
    /* 597 - Reserved46_IRQHandler */
    { &instanceList[597], &reviseItems[2750], 0x33542, 0x4ba, 12 },
    /* 598 - MAILBOX_IRQHandler */
    { &instanceList[598], &reviseItems[2751], 0x3354e, 0x4be, 12 },
    /* 599 - PIN_INT4_IRQHandler */
    { &instanceList[599], &reviseItems[2752], 0x3355a, 0x4c2, 12 },
    /* 600 - PIN_INT5_IRQHandler */
    { &instanceList[600], &reviseItems[2753], 0x33566, 0x4c6, 12 },
    /* 601 - PIN_INT6_IRQHandler */
    { &instanceList[601], &reviseItems[2754], 0x33572, 0x4ca, 12 },
    /* 602 - PIN_INT7_IRQHandler */
    { &instanceList[602], &reviseItems[2755], 0x3357e, 0x4ce, 12 },
    /* 603 - CTIMER2_IRQHandler */
    { &instanceList[603], &reviseItems[2756], 0x3358a, 0x4d2, 12 },
    /* 604 - CTIMER4_IRQHandler */
    { &instanceList[604], &reviseItems[2757], 0x33596, 0x4d6, 12 },
    /* 605 - OS_EVENT_IRQHandler */
    { &instanceList[605], &reviseItems[2758], 0x335a2, 0x4da, 12 },
    /* 606 - Reserved55_IRQHandler */
    { &instanceList[606], &reviseItems[2759], 0x335ae, 0x4de, 12 },
    /* 607 - Reserved56_IRQHandler */
    { &instanceList[607], &reviseItems[2760], 0x335ba, 0x4e2, 12 },
    /* 608 - Reserved57_IRQHandler */
    { &instanceList[608], &reviseItems[2761], 0x335c6, 0x4e6, 12 },
    /* 609 - SDIO_IRQHandler */
    { &instanceList[609], &reviseItems[2762], 0x335d2, 0x4ea, 12 },
    /* 610 - Reserved59_IRQHandler */
    { &instanceList[610], &reviseItems[2763], 0x335de, 0x4ee, 12 },
    /* 611 - Reserved60_IRQHandler */
    { &instanceList[611], &reviseItems[2764], 0x335ea, 0x4f2, 12 },
    /* 612 - Reserved61_IRQHandler */
    { &instanceList[612], &reviseItems[2765], 0x335f6, 0x4f6, 12 },
    /* 613 - USB1_PHY_IRQHandler */
    { &instanceList[613], &reviseItems[2766], 0x33602, 0x4fa, 12 },
    /* 614 - USB1_IRQHandler */
    { &instanceList[614], &reviseItems[2767], 0x3360e, 0x4fe, 12 },
    /* 615 - USB1_NEEDCLK_IRQHandler */
    { &instanceList[615], &reviseItems[2768], 0x3361a, 0x502, 12 },
    /* 616 - SEC_HYPERVISOR_CALL_IRQHandler */
    { &instanceList[616], &reviseItems[2769], 0x33626, 0x506, 12 },
    /* 617 - SEC_GPIO_INT0_IRQ0_IRQHandler */
    { &instanceList[617], &reviseItems[2770], 0x33632, 0x50a, 12 },
    /* 618 - SEC_GPIO_INT0_IRQ1_IRQHandler */
    { &instanceList[618], &reviseItems[2771], 0x3363e, 0x50e, 12 },
    /* 619 - PLU_IRQHandler */
    { &instanceList[619], &reviseItems[2772], 0x3364a, 0x512, 12 },
    /* 620 - SEC_VIO_IRQHandler */
    { &instanceList[620], &reviseItems[2773], 0x33656, 0x516, 12 },
    /* 621 - HASHCRYPT_IRQHandler */
    { &instanceList[621], &reviseItems[2774], 0x33662, 0x51a, 12 },
    /* 622 - CASER_IRQHandler */
    { &instanceList[622], &reviseItems[2775], 0x3366e, 0x51e, 12 },
    /* 623 - PUF_IRQHandler */
    { &instanceList[623], &reviseItems[2776], 0x3367a, 0x522, 12 },
    /* 624 - PQ_IRQHandler */
    { &instanceList[624], &reviseItems[2777], 0x33686, 0x526, 12 },
    /* 625 - DMA1_IRQHandler */
    { &instanceList[625], &reviseItems[2778], 0x33692, 0x52a, 12 },
    /* 626 - FLEXCOMM8_IRQHandler */
    { &instanceList[626], &reviseItems[2779], 0x3369e, 0x52e, 12 },
    /* 627 - post_semaph */
    { &instanceList[627], &reviseItems[2780], 0x336aa, 0x400, 10 },
    /* 628 - IPs_are_valid */
    { &instanceList[628], &reviseItems[2781], 0x336b4, 0x400, 54 },
    /* 629 - task_refresher */
    { &instanceList[629], &reviseItems[2782], 0x336ea, 0xc00, 38 },
    /* 630 - SystemInit */
    { &instanceList[630], &reviseItems[2785], 0x33710, 0x400, 4 },
    /* 631 - HardFault_Handler */
    { &instanceList[631], NULL, 0x33714, 0xe, 42 },
    /* 632 - __mqtt_next_pid */
    { &instanceList[632], &reviseItems[2786], 0x3373e, 0x400, 60 },
    /* 633 - mqtt_pack_ping_request */
    { &instanceList[633], &reviseItems[2787], 0x3377a, 0x800, 42 },
    /* 634 - mqtt_mq_init */
    { &instanceList[634], &reviseItems[2789], 0x337a4, 0x400, 30 },
    /* 635 - mqtt_mq_register */
    { &instanceList[635], &reviseItems[2790], 0x337c2, 0x400, 42 },
    /* 636 - mqtt_mq_find */
    { &instanceList[636], &reviseItems[2791], 0x337ec, 0x400, 52 },
    /* 637 - __mqtt_pack_uint16 */
    { &instanceList[637], &reviseItems[2792], 0x33820, 0x800, 30 },
    /* 638 - __mqtt_unpack_uint16 */
    { &instanceList[638], &reviseItems[2794], 0x3383e, 0x800, 36 },
    /* 639 - __mqtt_pack_str */
    { &instanceList[639], &reviseItems[2796], 0x33862, 0xc00, 56 },
    /* 640 - ulSetInterruptMask */
    { &instanceList[640], &reviseItems[2799], 0x3389a, 0x400, 24 },
    /* 641 - vClearInterruptMask */
    { &instanceList[641], &reviseItems[2800], 0x338b2, 0x400, 16 },
    /* 642 - vPortAllocateSecureContext */
    { &instanceList[642], &reviseItems[2801], 0x338c2, 0x400, 6 },
    /* 643 - vPortFreeSecureContext */
    { &instanceList[643], &reviseItems[2802], 0x338c8, 0x400, 14 },
    /* 644 - xEventGroupCreate */
    { &instanceList[644], &reviseItems[2803], 0x338d6, 0xc00, 38 },
    /* 645 - xEventGroupWaitBits */
    { &instanceList[645], &reviseItems[2806], 0x338fc, 0x3400, 260 },
    /* 646 - xEventGroupClearBits */
    { &instanceList[646], &reviseItems[2819], 0x33a00, 0x1400, 66 },
    /* 647 - vEventGroupClearBitsCallback */
    { &instanceList[647], &reviseItems[2824], 0x33a42, 0x400, 4 },
    /* 648 - xEventGroupSetBits */
    { &instanceList[648], &reviseItems[2825], 0x33a46, 0x1800, 134 },
    /* 649 - vEventGroupSetBitsCallback */
    { &instanceList[649], &reviseItems[2831], 0x33acc, 0x400, 4 },
    /* 650 - vEventGroupDelete */
    { &instanceList[650], &reviseItems[2832], 0x33ad0, 0x1400, 68 },
    /* 651 - vListInitialise */
    { &instanceList[651], &reviseItems[2837], 0x33b14, 0x400, 24 },
    /* 652 - vListInitialiseItem */
    { &instanceList[652], &reviseItems[2838], 0x33b2c, 0x400, 8 },
    /* 653 - vListInsertEnd */
    { &instanceList[653], &reviseItems[2839], 0x33b34, 0x400, 26 },
    /* 654 - vListInsert */
    { &instanceList[654], &reviseItems[2840], 0x33b4e, 0x400, 50 },
    /* 655 - uxListRemove */
    { &instanceList[655], &reviseItems[2841], 0x33b80, 0x400, 34 },
    /* 656 - prvIsQueueEmpty */
    { &instanceList[656], &reviseItems[2842], 0x33ba2, 0xc00, 34 },
    /* 657 - prvCopyDataToQueue */
    { &instanceList[657], &reviseItems[2845], 0x33bc4, 0x1000, 122 },
    /* 658 - prvCopyDataFromQueue */
    { &instanceList[658], &reviseItems[2849], 0x33c3e, 0x800, 46 },
    /* 659 - prvUnlockQueue */
    { &instanceList[659], &reviseItems[2851], 0x33c6c, 0x2000, 140 },
    /* 660 - xQueueGenericReset */
    { &instanceList[660], &reviseItems[2859], 0x33cf8, 0x2000, 130 },
    /* 661 - xQueueGenericCreate */
    { &instanceList[661], &reviseItems[2867], 0x33d7a, 0x1000, 76 },
    /* 662 - xQueueGetMutexHolder */
    { &instanceList[662], &reviseItems[2871], 0x33dc6, 0xc00, 38 },
    /* 663 - xQueueGenericSend */
    { &instanceList[663], &reviseItems[2874], 0x33dec, 0x7400, 392 },
    /* 664 - xQueueCreateMutex */
    { &instanceList[664], &reviseItems[2903], 0x33f74, 0x1000, 70 },
    /* 665 - xQueueGenericSendFromISR */
    { &instanceList[665], &reviseItems[2907], 0x33fba, 0x2000, 178 },
    /* 666 - xQueueGiveFromISR */
    { &instanceList[666], &reviseItems[2915], 0x3406c, 0x1c00, 146 },
    /* 667 - xQueueReceive */
    { &instanceList[667], &reviseItems[2922], 0x340fe, 0x6c00, 358 },
    /* 668 - xQueueSemaphoreTake */
    { &instanceList[668], &reviseItems[2949], 0x34264, 0x8800, 446 },
    /* 669 - vQueueDelete */
    { &instanceList[669], &reviseItems[2983], 0x34422, 0xc00, 34 },
    /* 670 - vQueueWaitForMessageRestricted */
    { &instanceList[670], &reviseItems[2986], 0x34444, 0x1000, 82 },
    /* 671 - findPll0PreDiv */
    { &instanceList[671], &reviseItems[2990], 0x34496, 0x800, 34 },
    /* 672 - CLOCK_SetClkDiv */
    { &instanceList[672], &reviseItems[2992], 0x344b8, 0x800, 40 },
    /* 673 - GPIO_PinInit */
    { &instanceList[673], &reviseItems[2994], 0x344e0, 0x400, 64 },
    /* 674 - INPUTMUX_Init */
    { &instanceList[674], &reviseItems[2995], 0x34520, 0x400, 16 },
    /* 675 - INPUTMUX_AttachSignal */
    { &instanceList[675], &reviseItems[2996], 0x34530, 0x400, 16 },
    /* 676 - INPUTMUX_Deinit */
    { &instanceList[676], &reviseItems[2997], 0x34540, 0x400, 16 },
    /* 677 - PINT_PatternMatchResetDetectLogic */
    { &instanceList[677], &reviseItems[2998], 0x34550, 0x400, 16 },
    /* 678 - PINT_PinInterruptClrStatus */
    { &instanceList[678], &reviseItems[2999], 0x34560, 0x400, 24 },
    /* 679 - RESET_PeripheralReset */
    { &instanceList[679], &reviseItems[3000], 0x34578, 0x800, 22 },
    /* 680 - SPI_SlaveTransferHandleIRQ */
    { &instanceList[680], &reviseItems[3002], 0x3458e, 0x400, 4 },
    /* 681 - SPI_EnableTxDMA */
    { &instanceList[681], &reviseItems[3003], 0x34592, 0x400, 24 },
    /* 682 - SPI_EnableRxDMA */
    { &instanceList[682], &reviseItems[3004], 0x345aa, 0x400, 24 },
    /* 683 - SpiConfigToFifoWR */
    { &instanceList[683], &reviseItems[3005], 0x345c2, 0x400, 36 },
    /* 684 - SPI_RxDMACallback */
    { &instanceList[684], &reviseItems[3006], 0x345e6, 0x800, 48 },
    /* 685 - SPI_TxDMACallback */
    { &instanceList[685], &reviseItems[3008], 0x34616, 0x800, 48 },
    /* 686 - XferToFifoWR.isra.0 */
    { &instanceList[686], &reviseItems[3010], 0x34646, 0x400, 26 },
    /* 687 - BOARD_InitBootClocks */
    { &instanceList[687], &reviseItems[3011], 0x34660, 0x400, 4 },
    /* 688 - BOARD_InitBootPeripherals */
    { &instanceList[688], &reviseItems[3012], 0x34664, 0x400, 4 },
    /* 689 - BOARD_InitPins */
    { &instanceList[689], &reviseItems[3013], 0x34668, 0x400, 28 },
    /* 690 - BOARD_InitBootPins */
    { &instanceList[690], &reviseItems[3014], 0x34684, 0x400, 4 },
    /* 691 - __main */
    { &instanceList[691], &reviseItems[3015], 0x34688, 0x800, 18 },
    /* 692 - __exit */
    { &instanceList[692], NULL, 0x3469a, 0x0, 2 },
    /* 693 - memcpy */
    { &instanceList[693], &reviseItems[3017], 0x3469c, 0x400, 4 },
    /* 694 - memmove */
    { &instanceList[694], &reviseItems[3018], 0x346a0, 0x400, 4 },
    /* 695 - memset */
    { &instanceList[695], &reviseItems[3019], 0x346a4, 0x400, 4 },
    /* 696 - _deferredlazyseek */
    { &instanceList[696], &reviseItems[3020], 0x346a8, 0x800, 72 },
    /* 697 - __flsbuf */
    { &instanceList[697], &reviseItems[3022], 0x346f0, 0x2000, 352 },
    /* 698 - _fflush */
    { &instanceList[698], &reviseItems[3030], 0x34850, 0x800, 90 },
    /* 699 - free */
    { &instanceList[699], &reviseItems[3032], 0x348aa, 0x400, 50 },
    /* 700 - fputs */
    { &instanceList[700], &reviseItems[3033], 0x348dc, 0x800, 52 },
    /* 701 - memcmp */
    { &instanceList[701], &reviseItems[3035], 0x34910, 0x400, 70 },
    /* 702 - no_fp_display */
    { &instanceList[702], &reviseItems[3036], 0x34956, 0x400, 6 },
    /* 703 - sscanf */
    { &instanceList[703], &reviseItems[3037], 0x3495c, 0x1000, 76 },
    /* 704 - setvbuf */
    { &instanceList[704], &reviseItems[3041], 0x349a8, 0x400, 66 },
    /* 705 - strcmp */
    { &instanceList[705], &reviseItems[3042], 0x349ea, 0x400, 72 },
    /* 706 - strcpy */
    { &instanceList[706], &reviseItems[3043], 0x34a32, 0x400, 70 },
    /* 707 - strlen */
    { &instanceList[707], &reviseItems[3044], 0x34a78, 0x400, 80 },
    /* 708 - strncpy */
    { &instanceList[708], &reviseItems[3045], 0x34ac8, 0x400, 92 },
    /* 709 - ungetc */
    { &instanceList[709], &reviseItems[3046], 0x34b24, 0x800, 54 },
    /* 710 - _Csys_read_ */
    { &instanceList[710], &reviseItems[3048], 0x34b5a, 0xc00, 42 },
    /* 711 - _fdopen */
    { &instanceList[711], &reviseItems[3051], 0x34b84, 0xc00, 116 },
    /* 712 - fclose */
    { &instanceList[712], &reviseItems[3054], 0x34bf8, 0x1c00, 116 },
    /* 713 - remove */
    { &instanceList[713], &reviseItems[3061], 0x34c6c, 0x800, 24 },
    /* 714 - _do_fflush */
    { &instanceList[714], &reviseItems[3063], 0x34c84, 0x1000, 80 },
    /* 715 - __aeabi_uldivmod */
    { &instanceList[715], &reviseItems[3067], 0x34cd4, 0x1800, 394 },
    /* 716 - __aeabi_idiv0 */
    { &instanceList[716], &reviseItems[3073], 0x34e5e, 0x400, 4 },
    /* 717 - __aeabi_d2iz */
    { &instanceList[717], &reviseItems[3074], 0x34e62, 0xc00, 70 },
    /* 718 - __aeabi_d2uiz */
    { &instanceList[718], &reviseItems[3077], 0x34ea8, 0x800, 52 },
    /* 719 - __aeabi_d2lz */
    { &instanceList[719], &reviseItems[3079], 0x34edc, 0x400, 118 },
    /* 720 - __bhs_ui2d */
    { &instanceList[720], &reviseItems[3080], 0x34f52, 0x400, 72 },
    /* 721 - __bhs_ul2d */
    { &instanceList[721], &reviseItems[3081], 0x34f9a, 0x400, 142 },
    /* 722 - __aeabi_i2d */
    { &instanceList[722], &reviseItems[3082], 0x35028, 0x400, 18 },
    /* 723 - __aeabi_ui2d */
    { &instanceList[723], &reviseItems[3083], 0x3503a, 0x400, 8 },
    /* 724 - __aeabi_l2d */
    { &instanceList[724], &reviseItems[3084], 0x35042, 0x400, 28 },
    /* 725 - __aeabi_dcmpeq */
    { &instanceList[725], &reviseItems[3085], 0x3505e, 0x400, 52 },
    /* 726 - __aeabi_dcmplt */
    { &instanceList[726], &reviseItems[3086], 0x35092, 0x400, 90 },
    /* 727 - __aeabi_dcmpgt */
    { &instanceList[727], &reviseItems[3087], 0x350ec, 0x400, 90 },
    /* 728 - __aeabi_dcmple */
    { &instanceList[728], &reviseItems[3088], 0x35146, 0x400, 90 },
    /* 729 - __aeabi_dcmpge */
    { &instanceList[729], &reviseItems[3089], 0x351a0, 0x400, 96 },
    /* 730 - __aeabi_memcpy */
    { &instanceList[730], &reviseItems[3090], 0x35200, 0x800, 56 },
    /* 731 - __aeabi_memcpy8 */
    { &instanceList[731], &reviseItems[3092], 0x35238, 0x800, 46 },
    /* 732 - __aeabi_memmove8 */
    { &instanceList[732], &reviseItems[3094], 0x35266, 0x800, 30 },
    /* 733 - __aeabi_lowlevel_memset */
    { &instanceList[733], &reviseItems[3096], 0x35284, 0x400, 52 },
    /* 734 - __sys_close */
    { &instanceList[734], &reviseItems[3097], 0x352b8, 0x400, 8 },
    /* 735 - __sys_flen */
    { &instanceList[735], &reviseItems[3098], 0x352c0, 0x400, 8 },
    /* 736 - __sys_istty */
    { &instanceList[736], &reviseItems[3099], 0x352c8, 0x400, 8 },
    /* 737 - __sys_read */
    { &instanceList[737], &reviseItems[3100], 0x352d0, 0x400, 6 },
    /* 738 - __readc */
    { &instanceList[738], &reviseItems[3101], 0x352d6, 0x400, 8 },
    /* 739 - __sys_remove */
    { &instanceList[739], &reviseItems[3102], 0x352de, 0x400, 8 },
    /* 740 - __sys_seek */
    { &instanceList[740], &reviseItems[3103], 0x352e6, 0x400, 8 },
    /* 741 - __sys_tmpnam */
    { &instanceList[741], &reviseItems[3104], 0x352ee, 0x400, 8 },
    /* 742 - __sys_write */
    { &instanceList[742], &reviseItems[3105], 0x352f6, 0x400, 6 },
    /* 743 - __SecureContext_SaveContext_veneer */
    { &instanceList[743], NULL, 0x352fe, 0x0, 18 },
    /* 744 - __SecureContext_FreeContext_veneer */
    { &instanceList[744], NULL, 0x35310, 0x0, 20 },
    /* 745 - __SecureContext_LoadContext_veneer */
    { &instanceList[745], NULL, 0x35324, 0x0, 20 },
    /* 746 - __SecureContext_Init_veneer */
    { &instanceList[746], NULL, 0x35338, 0x0, 20 },
    /* 747 - __SecureInit_DePrioritizeNSExceptions_veneer */
    { &instanceList[747], NULL, 0x3534c, 0x0, 20 },
    /* 748 - __SecureContext_AllocateContext_veneer */
    { &instanceList[748], NULL, 0x35360, 0x0, 20 },
    /* 749 - PendSV_Hook0_veneer */
    { &instanceList[749], NULL, 0x35374, 0x0, 8 },
    /* 750 - wfi_veneer */
    { &instanceList[750], NULL, 0x3537c, 0x0, 8 },
    /* 751 - return_veneer */
    { &instanceList[751], NULL, 0x35384, 0x0, 24 },
    /* 752 - indirect_call_veneer */
    { &instanceList[752], NULL, 0x3539c, 0x0, 8 },
    /* 753 - indirect_branch_veneer */
    { &instanceList[753], NULL, 0x353a4, 0x0, 40 },
};

#endif /* SOURCE_OBJECT_LIST_H_ */
