#ifndef SOURCE_OBJECT_LIST_H_
#define SOURCE_OBJECT_LIST_H_

/* DO NOT EDIT THIS FILE */

__attribute__((section(".data.$GLOBAL_REGION")))
instance_t instanceList[1];

const object_t objectList[] = {
	{ NULL, 0, 0, 0}
};

#endif /* SOURCE_OBJECT_LIST_H_ */
